### ISSUE TITLE
Energy pipe don´t transfer

### ISSUE THREAD

**Issue by Realever** [henkelmax/pipez#1]
hi,
i used your mod and the Energy pipe don´t transfer the power from the machines.
I clicked with the wrench on that side where the energy should be extract but it didn´t work.

Minecraft version: 1.16.5
Forge version: 1.16.5 - 36.0.22
Pipez version: [1.16.5] Pipez 1.16.5-1.0.3
screenshot: https://www.directupload.net/file/d/6091/mige38mi_png.htm

Edit: It seems that this error exist only on the server.When i test this on the lan world it´s working

**Comment by henkelmax** [comment]
Please follow the bug template and provide log files.

**Comment by Realever** [comment]
client latest log: https://gist.github.com/Realever/c79be98019fc760e37f9c0c3c8f0644d
debug server file: https://gist.github.com/Realever/1b3f0ee32363ad37c71c32e453a31afc
lastes sever log: https://gist.github.com/Realever/c10c7af3e758c84c9a4ebd9dd142472b

**Comment by henkelmax** [comment]
Which blocks did you use to extract energy?

**Comment by Realever** [comment]
the energy cell from thermal and the energy pipe from your mod to extract the power to the furnace

**Comment by Bommel24** [comment]
Can you verify:
1) that you don't have Redstone mode enabled on the extractor
2) You have the Redstone Flux Cell properly configured to output energy (and that it has energy)

If all of thi applies please attach a screeenshot of the extractor gui

**Comment by Realever** [comment]
sure.
Front picture: https://www.directupload.net/file/d/6091/mmgkjhs5_png.htm
Gui: https://www.directupload.net/file/d/6091/cgywah2g_png.htm

**Comment by Realever** [comment]
ok it´s working.The only think where it didn´t extract is the coal generator from rftools.But the rest is working.It was a stupid wired mistake from my side.Thank you guys for the help :)
