### ISSUE TITLE
How to route any items to a certain destination?

### ISSUE THREAD

**Issue by changhe3** [henkelmax/pipez#100]
Currently you need to input an item or tag to add a filter. I wonder if there's an option to allow all items but only send them to a certain destination.

**Comment by henkelmax** [comment]
You need to invert and set it to blacklist.

**Comment by changhe3** [comment]
Can you elaborate further? The "Add" button is greyed out if you don't input a valid item...

**Comment by henkelmax** [comment]
Then just put a dummy item in and invert it.
