### ISSUE TITLE
When block's fluid is null, server will be crash

### ISSUE THREAD

**Issue by TheSmileCat** [henkelmax/pipez#103]
**Bug description**

The text below...

**Steps to reproduce the issue**

When I changed the mode of the fluid pipe to extraction mode, the server crashed due to NPE problems and the target box was advgenerators:fluid_input（the **Fluid Intake Valve** of **Advanced Generators** mod）

**Expected behavior**

The server has failed to start (block near birth point)

**Log files**

![image](https://user-images.githubusercontent.com/53056806/158242245-d772430e-2265-4c86-9f7d-bbb9f95538fa.png)

**Versions**
- Minecraft version : 1.18.1
- Forge version : 39.1.2
- Mod version : 1.0.1

**Other mods**

Advanced Generators (author: bdew)
[mods.txt](https://github.com/henkelmax/pipez/files/8247937/mods.txt)

**Screenshots (Optional)**
![179Z MHYJ7{VK~VIUN$V{ D](https://user-images.githubusercontent.com/53056806/158244334-d9167b97-14cb-4cb0-a0b0-36cf077c4543.png)
![G`B}$HUREY8WD$IFVP4JYHW](https://user-images.githubusercontent.com/53056806/158244353-50d76118-98fd-4d34-8fb8-56de3a5dff06.png)

**Comment by henkelmax** [comment]
Fluids should never be null. No fluid means Fluids.EMPTY
![image](https://user-images.githubusercontent.com/13237524/158245444-60d5426b-f391-43c0-be85-dcc316518878.png)
