### ISSUE TITLE
Round and robin doesnt porovide enough energy on "komplex" Energy Pipe System

### ISSUE THREAD

**Issue by J3asti** [henkelmax/pipez#107]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Round and Robin on Energy Pipes doesnt transfer enough energy

**Steps to reproduce the issue**
1. world config: change [energy_pipe.amount] no_upgrade = 4000000 (or something else high)
2. Put Energy Pipe on a Battery or Reactor (which can support so much energy) and branch the cable out like a twig. Something goes to Garden cloches something to mekanism machines something to the ME Controller.
3. All machines with high energy usage dont get enough energy.

**Expected behavior**
All Machines should get enugh energy. If i put in an improved upgrade and change the value for improved upgrades to 4m rf/t and change the pipe to nearest first it works fine. But round and robin is not providing enugh energy.
Let us change in the config the base value for no_upgrade pipes. So that we can use Nearest first on non upgraded pipes. 

**Versions**
- 1.18.2
- 40.0.54
- 1.0.3

**Other mods**
Mekanism
Immersive Engineering
Applied Energistics 2
![2022-04-21_10 30 55](https://user-images.githubusercontent.com/103183872/164414878-357722b9-e638-406f-b709-90c2462c5ac5.png)

**Comment by henkelmax** [comment]
The whole point of upgrades is that you have certain functionality locked.

> Let us change in the config the base value for no_upgrade pipes.

What do you mean? This is already a thing.


Can you please elaborate further what the bug is in your setup?

**Comment by J3asti** [comment]
Okay. Did some screenshots to explain my point even more. By making this Setup i found out that the mod realy isnt made for huge amount of energy. But here we go.
This is the Setup. Just some little things what could be in a base setup:

![Setup](https://user-images.githubusercontent.com/103183872/164442802-66d2ab00-620c-423d-9884-0087e6445c85.png)

And here is the config for Energy Pipes:

![Pipez Settings](https://user-images.githubusercontent.com/103183872/164443720-49f12b5b-a7a1-4454-854a-7e48d63ea5a2.PNG)

If i put the Energy Output to Round and robin with an Ultimate Pipe Upgrade, the machine with the most power draw does not get enough energy. (For this demonstration we are looking to the fulle upgraded Rotary Condensator with 8x Speed & 8x Energy Upgrades; Total Power Draw: 51.2k FE/t)

![Round Energy](https://user-images.githubusercontent.com/103183872/164444415-e41695ba-f98a-43f4-963a-66a021d966c1.png)

With Nearest First it is somehow stable.

![Nearest Energy](https://user-images.githubusercontent.com/103183872/164444894-d1f81fba-95af-4269-a2cf-0ada82d1c3aa.png)

Even with Nearest its still not quite full. If i connect the machine directly to the power output with the cable it works fine:

![Just 1 connection](https://user-images.githubusercontent.com/103183872/164445485-6e8a7777-b644-4123-9d26-18fae5b90179.png)

I think its something with the complexity of the cables.

**Comment by henkelmax** [comment]
I'm pretty sure this is caused by the rate, the pipe can take out energy from the source.
Pipes takes the whole amount it can get from the source, splits it by the amount of consumers, distributes that evenly and everything that couldn't be inserted in sources that are already full gets distributed for the rest of all consumers (This is repeated until all energy is distributed).
So the only explanation why this could happen is the rate your source provides energy.
Try using the creative energy cube (whatever its called) from mekanism.

**Comment by J3asti** [comment]
> Try using the creative energy cube (whatever its called) from mekanism.
Already Using it in my Setup i posted

**Comment by henkelmax** [comment]
Can you provide a very minimal setup, where this happens, so I can reproduce it?
It would be best if you could do it with just Pipez and Mekanism

**Comment by J3asti** [comment]
![Basic](https://user-images.githubusercontent.com/103183872/164448286-508706f7-1329-49a5-bad7-c0b4ba3b0564.png)

Thats it. Keep in mind everything is upgraded to 8x Energy & 8x Speed

**Comment by henkelmax** [comment]
I tested your setup and I can confirm that this happens, but then I tried it with the mekanism cables and the same thing happens:

![image](https://user-images.githubusercontent.com/13237524/164668466-dd2db873-c478-43f3-84c5-77785498b5a9.png)

![image](https://user-images.githubusercontent.com/13237524/164668745-7ffb633b-a28f-4e20-a578-e791be34c83c.png)

**Comment by henkelmax** [comment]
I even went in the code with the debugger and checked what amount of energy is arriving at the machines. Pipez attempts to insert the correct amount of energy proportional to the amount of energy extracted. No clue why this happens, but my hunch is that the buffer of the machines is too small to maintain full energy. I'm assuming the machines are taking out the energy before the pipe is putting in energy within that tick.

**Comment by henkelmax** [comment]
Closed due to inactivity
