### ISSUE TITLE
Ability to filter any item by NBT only

### ISSUE THREAD

**Issue by jackwright-ual** [henkelmax/pipez#11]
Any chance you'd consider adding this?

**Comment by jackwright-ual** [comment]
> maybe you could filter by item name with regex?

**Comment by henkelmax** [comment]
Thank you for submitting this!

![image](https://user-images.githubusercontent.com/13237524/111618552-cd349280-87e4-11eb-957f-8fc96bde31d8.png)
![image](https://user-images.githubusercontent.com/13237524/111618578-d45ba080-87e4-11eb-8e11-9d881a8b41e8.png)

Should work now.
