### ISSUE TITLE
all pipes don't work at all

### ISSUE THREAD

**Issue by Porkemon211** [henkelmax/pipez#112]
**Bug description**
i'm trying to use the item pipes to transfer from one chest to another one and i cant make the pipe on the first chest to expell items going into the mod config in game don't resolve anything couse it tell me that "data for this config hasn't been loaded yet" please help me find out what's wrong and how to resolve it

**Steps to reproduce the issue**
1. I place the item pipe on a chest
2. tried to click with the pipe wrench on the pipe to make it export items
3. nothing happend at all

**Expected behavior**
to work(?)

**Log files**
I dont know how to find and what should i search inside that

**Versions**
- Minecraft version 1.18.2
- Forge version 40.1.0
- Mod version 1.1.3

**Other mods**
Additional Enchanted Miner
Kotori316
AdditionalEnchantedMiner-1.18.2-18.9.jar

Applied Energistics 2
AlgorithmX2
appliedenergistics2-11.0.0-alpha.4.jar

Balm (Forge Edition)
BlayTheNinth
balm-3.0.2+0.jar

Chisels & Bits - For Forge
AlgorithmX2
ChiselsBits-forge-1.18.2-1.2.84-universal.jar

Cooking for Blockheads
BlayTheNinth
cookingforblockheads-forge-1.18.2-12.0.0.jar

CraftTweaker
Jaredlll08
CraftTweaker-forge-1.18.2-9.1.108.jar

Create Crafts & Additions
MRHminer
createaddition-1.18.2-20220419a.jar

EnderChests
ShetiPhian
enderchests-1.18-1.9.4.jar

EnderTanks
ShetiPhian
endertanks-1.18-1.11.5.jar

Extreme Reactors
ZeroNoRyouki
ExtremeReactors2-1.18.2-2.0.41.jar

FramedBlocks
XFactHD
FramedBlocks-5.1.0.jar

Integrated Dungeons and Structures
craisinlord
idas_forge-1.0.8+1.18.2.jar

Kotlin for Forge
thedarkcolour
kotlinforforge-3.2.0-obf.jar

KubeJS (Forge)
LatvianModder
kubejs-forge-1802.5.1-build.348.jar

Modern UI
BloCamLimb
ModernUI-1.18.2-3.4.3.102-universal.jar

Selene Lib
MehVahdJukaar
selene-1.18.2-1.15.4.jar

ShetiPhianCore
ShetiPhian
shetiphiancore-1.18-3.10.8.jar

Shrines Structures
silverminer007
Shrines-1.18.2-4.0.0-alpha2.jar

Structure Gel API
ModdingLegacy
structure_gel-1.18.2-2.2.2.jar

Valhelsia Core
ValhelsiaTeam
valhelsia_core-forge-1.18.2-0.3.0.jar

ZeroCore 2
ZeroNoRyouki
ZeroCore2-1.18.2-2.1.15.jar

[Forge] Expanded Storage
NinjaPhenix
expandedstorage-7.3.11+1.18.2.jar

Additional Additions | Forge
dqu1jjj
additionaladditions-3.0.1.1.jar

Additional Bars - Biomes O' Plenty addon
Gamma1772
additionalbarsbop-3.0.1-beta+1.18.2.jar

Additional Bars [FORGE]
Gamma1772
additionalbars-3.0.1-beta+1.18.2.jar

Additional Lanterns
SuperMartijn642
additionallanterns-1.0.1-mc1.18.jar

Additional Structures
XxRexRaptorxX
Rex's-AdditionalStructures-1.18.2-(v.3.0.3).jar

Adorn (Forge)
Juicebus
Adorn-3.4.0+1.18.2-forge.jar

Advanced Chimneys
EnderLanky
AdChimneys-1.18.2-8.0.0.0-build.0256.jar

Advanced Generators
bdew
advgenerators-1.1.0.5-mc1.18.2.jar

Age of Weapons
XxRexRaptorxX
AgeOfWeapons-Reforged-1.18.2-(v.0.3.2).jar

Akashic Tome
Vazkii
AkashicTome-1.5-20.jar

Alex's Mobs
sbom_xela
alexsmobs-1.17.5.jar

All The Tweaks
thevortexFoxTopia
allthetweaks-1.8.8-1.18.2-40.1.0.jar

AppleSkin
squeek502
appleskin-forge-mc1.18-2.4.0.jar

Aquaculture 2
Shadowclaimer
Aquaculture-1.18.2-2.3.6.jar

Architectury API (Forge)
shedaniel
architectury-4.2.50.jar

Ars Nouveau
baileyholl2
ars_nouveau-1.18.2-2.4.0.jar

ATO - All the Ores
ATMTeam
alltheores-1.9.4-1.18.2-40.1.0.jar

AutoRegLib
Vazkii
AutoRegLib-1.7-53.jar

BdLib
bdew
bdlib-1.19.3.7-mc1.18.2.jar

Bedspreads (Forge)
TheIllusiveC4
bedspreads-forge-1.18.1-5.1.0.5.jar

Better Mods Button [Forge]
Fuzs_
BetterModsButton-v3.2.1-1.18.2-Forge.jar

BetterF3
cominixo
BetterF3-1.2.4-Forge-1.18.2.jar

Bigger Reactors
RogueLogix
biggerreactors-1.18.2-0.6.0-beta.1.jar

BiomeInfo
bl4ckscor3
biomeinfo-1.18.2-1.4.jar

Biomes O' Plenty
Forstride
BiomesOPlenty-1.18.2-16.0.0.109-universal.jar

Blue Skies
ModdingLegacy
blue_skies-1.18.2-1.3.10.jar

Bonsai Trees 3
davenonymous
bonsaitrees3-3.1.0.jar

Bookshelf
DarkhaxDev
Bookshelf-Forge-1.18.2-13.0.13.jar

Building Gadgets
Direwolf20
buildinggadgets-3.13.0-build.5+mc1.18.2.jar

Carry On
Tschipp
carryon-1.18.2-1.17.0.8.jar

Citadel
sbom_xela
citadel-1.11.2-1.18.2.jar

Cloth Config API (Fabric/Forge)
shedaniel
cloth-config-6.2.57-forge.jar

Clumps
Jaredlll08
Clumps-forge-1.18.2-8.0.0+8.jar

Collective (Forge)
Serilum
collective-1.18.2-4.25.jar

Config Menus for Forge
Fuzs_
ConfigMenusForge-v3.2.0-1.18.2-Forge.jar

Configured
MrCrayfish
configured-1.5.3-1.18.2.jar

ConnectedTexturesMod
tterrag1098
CTM-1.18.2-1.1.4+4.jar

Controlling
Jaredlll08
Controlling-forge-1.18.2-9.0+19.jar

Crafting Tweaks
BlayTheNinth
craftingtweaks-forge-1.18.1-14.0.2.jar

Create
simibubi
create-mc1.18.2_v0.4.1.jar

CreateTweaker
Jaredlll08
CreateTweaker-1.18.2-2.0.0.9.jar

Croptopia [FABRIC/FORGE]
thethonk
Croptopia-1.18.2-FORGE-1.8.3.jar

Cucumber Library
BlakeBr0
Cucumber-1.18.2-5.1.0.jar

Culinary Construct
TheIllusiveC4
culinaryconstruct-forge-1.18.2-4.3.1.0.jar

Curios API (Forge)
TheIllusiveC4
curios-forge-1.18.2-5.0.7.0.jar

Cyclic
Lothrazar
Cyclic-1.18.2-1.6.18.jar

Dark Utilities
DarkhaxDev
DarkUtilities-Forge-1.18.2-10.0.4.jar

Decorative Blocks
stohun
Decorative Blocks-forge-1.18.2-2.1.0.jar

Disenchantment Edit Table
ji_GGO
DisenchantmentEditTable-1.18.1-1.0.7.jar

Durability Tooltip
SuperMartijn642
durabilitytooltip-1.1.0-mc1.18.jar

Easy Villagers
henkelmax
easy_villagers-1.18.2-1.0.4.jar

Eating Animation [Forge]
matyrobbrt
eatinganimation-1.18.1-2.0.2.jar

Enchanting Infuser [Forge]
Fuzs_
EnchantingInfuser-v3.2.0-1.18.2-Forge.jar

Enchantment Descriptions
DarkhaxDev
EnchantmentDescriptions-Forge-1.18.2-10.0.2.jar

Epic Knights: Shields, Armor and Weapons
magistu_
[1.18.x]-Epic-Knights-Armor-and-Weapons-5.10v.jar

Extra Disks
MelanX
ExtraDisks-1.18.2-2.1.0.jar

ExtraStorage
3divad99
ExtraStorage-1.18.2-2.1.0.jar

Extreme sound muffler (Forge)
LeoBeliik
extremeSoundMuffler-3.24_Forge-1.18.1.jar

Farmer's Delight
vectorwing
FarmersDelight-1.18.2-1.1.0.jar

Farming for Blockheads
BlayTheNinth
farmingforblockheads-forge-1.18.2-10.0.1.jar

Fast Leaf Decay
olafskiii
FastLeafDecay-28.jar

FastFurnace
Shadows_of_Fire
FastFurnace-1.18.2-6.0.3.jar

FastWorkbench
Shadows_of_Fire
FastWorkbench-1.18.2-6.0.2.jar

Feature NBT Deadlock Be Gone
telepathicgrunt
feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar

FlashFyre's Enchantments
f1ashfyre
ffenchantments-1.18.2-1.5.1.jar

Flat Bedrock
Sunekaer
flatbedrock-1.4.2-build.9+mc1.18.2.jar

Flywheel
jozufozu
flywheel-forge-1.18-0.6.2.jar

ForgeEndertech
EnderLanky
ForgeEndertech-1.18.2-9.0.0.0-build.0256.jar

Forgiving Void
BlayTheNinth
forgivingvoid-forge-1.18.1-6.0.1.jar

Framed Compacting Drawers
Eutropium
framedcompactdrawers-1.18-4.0.2.jar

Framework
MrCrayfish
framework-0.2.3-1.18.2.jar

FRV Tools
Feroov
FRV Tools-1.18.2-1.3.0.jar

FTB Chunks (Forge)
FTB
ftb-chunks-forge-1802.3.5-build.130.jar

FTB Library (Forge)
FTB
ftb-library-forge-1802.3.6-build.115.jar

FTB Teams (Forge)
FTB
ftb-teams-forge-1802.2.6-build.51.jar

FTB Ultimine (Forge)
FTB
ftb-ultimine-forge-1802.3.3-build.55.jar

Game Menu Mod Option [Forge]
morimori0317
GameMenuModOption-1.18-Forge-1.14.jar

GeckoLib
ThanosGecko
geckolib-1.18-forge-3.0.15.jar

Goblin Traders
MrCrayfish
goblintraders-1.7.1-1.18.2.jar

GraveStone Mod
henkelmax
gravestone-1.18.2-1.0.1.jar

Guard Villagers
almightytallestred
guardvillagers-1.18.2.1.4.1.jar

HT's TreePlant
hammertater
TreePlant-1.18.2-0.3.0.jar

I Like Wood
yamahari_
ilikewood-1.18.2-8.5.0.2.jar

I Like Wood - Biomes O' Plenty Plugin
yamahari_
ilikewoodxbiomesoplenty-1.18.2-8.0.0.jar

Infinite Trading (Forge)
Serilum
infinitetrading_1.18.2-2.0.jar

Inventory HUD+
dmitrylovin
InventoryHud_[1.18].forge-3.4.4.jar

Iron Furnaces [FORGE]
XenoMustache
ironfurnaces-1.18.2-3.2.1.jar

ItemZoom
mezz
itemzoom-1.18.2-2.6.0.jar

Jade 🔍
Snownee_
Jade-1.18.2-5.0.1.jar

JEITweaker
Jaredlll08
JEITweaker-1.18.2-3.0.0.8.jar

JourneyMap
techbrew
journeymap-1.18.2-5.8.2-forge.jar

Jump Over Fences
Kreezxil
jumpoverfences-1.18-1.0.1.jar

Just Enough Items (JEI)
mezz
jei-1.18.2-9.7.0.193.jar

Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.18.2-0.14.1.167.jar

Kiwi 🥝 (Forge)
Snownee_
Kiwi-1.18.2-forge-6.1.0.jar

KleeSlabs
BlayTheNinth
kleeslabs-forge-1.18.1-11.1.0.jar

KubeJS Create
LatvianModder
kubejs-create-1802.2.1-build.16.jar

Libnonymous
davenonymous
libnonymous-2.1.0.jar

Light Overlay (Rift/Forge/Fabric)
shedaniel
light-overlay-6.0.5-forge.jar

Lighting Wand 🌟 (Forge)
Snownee_
LightingWand-1.18.2-forge-4.0.0.jar

Macaw's Bridges
sketch_macaw
mcw-bridges-2.0.2-mc1.18.2.jar

Macaw's Bridges - Biome O' Plenty
samlegamer_
macawsbridgesbop-1.18.2-1.0.jar

Macaw's Doors
sketch_macaw
mcw-doors-1.0.6-mc1.18.2.jar

Macaw's Fences - Biomes O' Plenty
samlegamer_
mcwfencesbop-1.18.2-1.1.jar

Macaw's Fences and Walls
sketch_macaw
mcw-fences-1.0.4-mc1.18.2.jar

Macaw's Furniture
sketch_macaw
mcw-furniture-3.0.0-mc1.18.2.jar

Macaw's Lights and Lamps
sketch_macaw
mcw-lights-1.0.3-mc1.18.2.jar

Macaw's Roofs
sketch_macaw
mcw-roofs-2.1.2-mc1.18.2.jar

Macaw's Roofs - Biomes O' Plenty
samlegamer_
macawsroofsbop-1.18.2-1.0.jar

Macaw's Trapdoors
sketch_macaw
mcw-trapdoors-1.0.5-mc1.18.2.jar

Macaw's Windows
sketch_macaw
mcw-windows-2.0.3-mc1.18.2.jar

MCA Reborn [Fabric/Forge]
jahx_senpoopie
minecraft-comes-alive-7.2.1+1.18.2-forge.jar

McJtyLib
McJty
mcjtylib-1.18-6.0.13.jar

Mekanism
bradyaidanc
Mekanism-1.18.2-10.2.0.459.jar

Mekanism Additions
bradyaidanc
MekanismAdditions-1.18.2-10.2.0.459.jar

Mekanism Generators
bradyaidanc
MekanismGenerators-1.18.2-10.2.0.459.jar

Mekanism Tools
bradyaidanc
MekanismTools-1.18.2-10.2.0.459.jar

Mob Grinding Utils
vadis365
mob_grinding_utils-1.18.2-0.4.36.jar

Mod Name Tooltip
mezz
modnametooltip-1.18.1-1.18.0.jar

More Mekanism Processing
지젤쟝다
MoreMekanismProcessing-1.18.2-2.1.jar

More Overlays Updated
RiDGo8
moreoverlays-1.20.5-mc1.18.1.jar

More Storage Drawers
RydelFox
morestoragedrawers-1.18.2-1.1.2.jar

More Villagers
SameDifferent
morevillagers-FORGE-1.18.2-3.2.0.jar

Mouse Tweaks
YaLTeR
MouseTweaks-forge-mc1.18-2.21.jar

MrCrayfish's Furniture Mod
MrCrayfish
cfm-7.0.0-pre29-1.18.2.jar

MrCrayfish's Gun Mod
MrCrayfish
cgm-1.2.1-1.18.2.jar

Nameless Trinkets
Cozary
Nameless Trinkets-1.18.2-1.5.3.jar

Nature's Compass
Chaosyr
NaturesCompass-1.18.2-1.9.5-forge.jar

Neat
Vazkii
Neat 1.8-30.jar

NinjaPhenix's Container Library
NinjaPhenix
ninjaphenix-container-library-1.3.0+1.18-forge.jar

No Villager Death Messages
MutantGumdrop
novillagerdm-1.18.1-3.0.0.jar

Not Enough Crashes (Forge)
NatanFudge
notenoughcrashes-4.1.4+1.18.2-forge.jar

Oculus
Asek3
oculus-mc1.18.2-1.2.2b.jar

OpenBlocks Elevator
vsngarcia
elevatorid-1.18.2-1.8.4.jar

Patchouli
Vazkii
Patchouli-1.18.2-67.jar

Phosphophyllite
RogueLogix
phosphophyllite-1.18.2-0.6.0-beta.1.1.jar

Pickle Tweaks
BlakeBr0
PickleTweaks-1.18.2-6.1.0.jar

Pig Pen Cipher
DarkhaxDev
PigPen-Forge-1.18.2-8.0.1.jar

Pipez
henkelmax
pipez-1.18.2-1.1.3.jar

Placebo
Shadows_of_Fire
Placebo-1.18.2-6.2.1.jar

Polymorph (Forge)
TheIllusiveC4
polymorph-forge-1.18.1-0.43.jar

Portable Crafting Table
00theblackwolf00
PortableCraftingTable-1.18.2-3.0.2.jar

Potions Master
thevortexFoxTopia
potionsmaster-0.5.8-1.18.2-40.1.0.jar

Prefab
wuestman
prefab-1.8.2.1.jar

ProjectE
SinKillerJ
ProjectE-1.18.2-PE1.0.1.jar

Puzzles Lib [Forge]
Fuzs_
PuzzlesLib-v3.3.2-1.18.2-Forge.jar

Quark
Vazkii
Quark-3.2-350.jar

Quark Oddities
Vazkii
QuarkOddities-1.18.jar

Quartz
RogueLogix
quartz-1.18.2-0.0.0-beta.1.1.jar

Refined Storage
raoulvdberge
refinedstorage-1.10.2.jar

Refined Storage Addons
raoulvdberge
refinedstorageaddons-0.8.2.jar

RFTools Base
McJty
rftoolsbase-1.18-3.0.7.jar

RFTools Builder
McJty
rftoolsbuilder-1.18-4.0.9.jar

RFTools Control
McJty
rftoolscontrol-1.18-5.0.4.jar

RFTools Dimensions
McJty
rftoolsdim-1.18-8.0.4.jar

RFTools Power
McJty
rftoolspower-1.18-4.0.4.jar

RFTools Storage
McJty
rftoolsstorage-1.18-3.0.7.jar

RFTools Utility
McJty
rftoolsutility-1.18-4.0.14.jar

Rhino
LatvianModder
rhino-forge-1801.1.9-build.135.jar

Riddle Chests
davenonymous
riddlechests-2.1.0.jar

Rubidium
Asek3
rubidium-0.5.2a.jar

Runelic
DarkhaxDev
Runelic-Forge-1.18.2-11.0.1.jar

Scalable Cat's Force
Kotori316
ScalableCatsForce-2.13.8-build-4-with-library.jar

Silent Gear
SilentChaos512
silent-gear-1.18.2-2.10.0.jar

Silent Lib (silentlib)
SilentChaos512
silent-lib-1.18.2-6.2.0.jar

Simply Light
Flanks255
simplylight-1.18.2-1.4.2-build.31.jar

Skin Layers 3D (Fabric/Forge)
tr9zw
3dskinlayers-forge-1.4.3-mc1.18.2.jar

Snad
TheRoBrit
Snad-1.18.2-1.22.04.15a.jar

So Many Enchants
yeetmanlord
so_many_enchants-1.3.1.jar

Storage Drawers
Texelsaur
StorageDrawers-1.18.2-10.2.0.jar

SuperMartijn642's Config Lib
SuperMartijn642
supermartijn642configlib-1.0.9-mc1.18.jar

SuperMartijn642's Core Lib
SuperMartijn642
supermartijn642corelib-1.0.16b-mc1.18.jar

Supplementaries
MehVahdJukaar
supplementaries-1.18.2-1.3.7.jar

TerraBlender (Forge)
TheAdubbz
TerraBlender-forge-1.18.2-1.1.0.99.jar

The Undergarden
Quek04
The_Undergarden-1.18.2-0.7.0.jar

Toast Control
Shadows_of_Fire
ToastControl-1.18.2-6.0.2.jar

Tom's Simple Storage Mod
tom54541
toms_storage-1.18.2-1.3.0.jar

Trading Post [Forge]
Fuzs_
TradingPost-v3.2.0-1.18.2-Forge.jar

Trash Cans
SuperMartijn642
trashcans-1.0.14-mc1.18.jar

TrashSlot
BlayTheNinth
trashslot-forge-1.18.1-11.0.2.jar

Tree Harvester (Forge)
Serilum
treeharvester_1.18.2-5.1.jar

U Team Core
HyCraftHD
u_team_core-1.18.2-4.0.0.204.jar

Universal Bone Meal [Forge]
Fuzs_
UniversalBoneMeal-v3.0.3-1.18.2-Forge.jar

Useful Backpacks
HyCraftHD
useful_backpacks-1.18.2-1.12.1.93.jar

Useful Hats
thecech12
usefulhats-1.18.2-2.0.2.0.jar

Valhelsia Structures
ValhelsiaTeam
valhelsia_structures-forge-1.18.2-0.1.0.jar

Village Artifacts
Lothrazar
villagertools-1.18-1.0.2.jar

Village Spawn Point (Forge)
Serilum
villagespawnpoint_1.18.2-1.9.jar

Wall-Jump! [FORGE]
genandnic
walljump-forge-1.18.1-1.3.7.jar

Wandering Bag
Furti_Two
wandering-bag-1.18.2-1.0.3.jar

What's That Slot?
gegy1000
whats-that-slot-forge-1.2.3+1.18.1.jar

When Dungeons Arise - Forge!

**Comment by henkelmax** [comment]
Please fill out the bug template.

**Comment by Porkemon211** [comment]
@henkelmax is this better?

**Comment by henkelmax** [comment]
Please provide logs and screenshots

**Comment by henkelmax** [comment]
Closed due to inactivity
