### ISSUE TITLE
Please add description including rates

### ISSUE THREAD

**Issue by Flachdachs** [henkelmax/pipez#113]
Could you please add some description to the pipe items and upgrades, especially telling the user the transfer rates.

**Comment by henkelmax** [comment]
This is already a thing.
Install JEI, Jade or The one Probe.

**Comment by Flachdachs** [comment]
Sorry then, must be a problem at my side. I have JEI installed, but only see a description for the wrench and filter tool.

**Comment by Flachdachs** [comment]
Now I see. There is no description in JEI when hovering over the item. Only when placed in the world and made it an extraction end using the wrench. Then you can see at this end the rate.

I was looking in JEI itself, some other mods have a short descriptions for their items. Also the descriptions in CurseForge and ModRepo have no (default) numbers listed.
