### ISSUE TITLE
add mekanism "gas" api

### ISSUE THREAD

**Issue by killmetohell** [henkelmax/pipez#115]
The title is misleading but I discover mekanism gases well at least pressure tube that transfer the gases is actually use more than the gas api i found this out when i lookup xnet gases a mod add-on and in the description that it uses slurry api.
I have used the gas pipe from this mod i found it doesn't work so i assuming it doesn't add slurry api.
I also look up issues just in case if anyone one else having the same problem and i found something similar #38 .
since pipez add support for gas for mekanism why not add the other apis that mekanism uses for the pressurized tubes to make it less confusing to players who use this mod when they try it.
I don't know what are the all apis that mekanism uses for their tubes ones i know so far are
- gases
- slurry
- pigment
- infuse? idk on that
if it possible can you add the all apis for mekanism pressurized tube uses?

**Comment by henkelmax** [comment]
Due to the implementation of the Pipez mod, it is not possible to have one type of pipes to handle multiple contents. And adding a new pipe just for slurries is overkill.
Also Mekanism has two completely separate APIs for slurries and gasses, despite them working with one pipe.

Its simply not worth the effort to implement it.

**Comment by markaabo** [comment]
Support for slurries would be nice, and the others to make this mod completely replace all need for mekanism pipez which helps with lag which is something you advertise on the mods descripion :)

**Comment by SmileycorpMC** [comment]
Considering mekanism pressurized pipes are completely broken this feels needed and justified.
