### ISSUE TITLE
Feature Request: Disable exporting for some pipe type in universal pipe

### ISSUE THREAD

**Issue by Jared87** [henkelmax/pipez#116]
I have an mashine and use the universal pipe extract fluids and items, but i would like to use the same pipe element to provide power.

This could be possibe with adding an button in the universal gui for disabling the extract of an specific pipe type.

**Comment by itsjusttriz** [comment]
i usually just set un-needed pipe types to redstone-required.. but, if you have a redstone signal nearby, this **would** be a handy thing to have.

**Comment by henkelmax** [comment]
You can just set the redstone mode to always off.

**Comment by itsjusttriz** [comment]
> You can just set the redstone mode to always off.

that doesnt disable the pipe tho.. i turn redstone always on, to "disable" the pipe... but if i have a redstone signal next to it, and i NEED the pipe to not function.. the requested feature would come in handy.

**Comment by henkelmax** [comment]
![image](https://github.com/henkelmax/pipez/assets/13237524/912bb9b3-1c34-41f4-afac-9dc6c1eed06d)
