### ISSUE TITLE
remove the need for mekanism to utilise the gas pipe

### ISSUE THREAD

**Issue by SpiderKraken** [henkelmax/pipez#117]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]advanced generator in 1.18.2 cannot integrate with almost any other mods for transferring syngas. i installed pipez to use the gas pipe but i do not want mekanism installed.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. i would like for the gas pipe to be able to work with syngas so i can actually use the generator 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. i have tried all available mods for 1.18.2 to move this syngas and all of them are borked or just dont work.

**Additional context**

**Comment by henkelmax** [comment]
The gas pipe is only for Mekanism gas. 
But Mekanism is completely optional. You don't need to install it.

**Comment by SpiderKraken** [comment]
I'm aware but that doesn't solve the problem of needing to move steam and syngas in advanced generators without mekanism. The fluid pipes don't work for it either.

**Comment by henkelmax** [comment]
We don't plan on adding support for other gasses than Mekanism
