### ISSUE TITLE
Fluid Pipe reverts to default state upon world load or block update

### ISSUE THREAD

**Issue by adammbaker** [henkelmax/pipez#12]
**Bug description**
Fluid Pipe set in extract mode to a [Mekanism Thermal Evaporation Plant](https://wiki.aidancbrady.com/wiki/Thermal_Evaporation_Plant)'s (TEP) Thermal Evaporation Valve reverts to its default state when the TEP has a layer added to it (changes its block state) or upon loading the world from a save.

**Steps to reproduce the issue**
1. Set up a functioning TEP as outlined in the above link.
2. Connect a Fluid Pipe to a Thermal Evaporation Valve and set it to extract mode.
3. Either reload the world or add another layer (12 Thermal Evaporation Blocks) to the TEP.

**Expected behavior**
I would expect a Fluid Pipe set to extract mode to retain its mode regardless of the block it is up against.

**Log files**
The game didn't crash so I don't think I would have a log for this bug.

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.0.46
- Mod version: pipez-1.16.5-1.1.2 as contained in [All The Mods 6 - To The Sky - ATM6S 1.0.2](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6-to-the-sky-atm6s/files)

**Other mods**
Again, this is used in All The Mods 6 - To The Sky - ATM6S 1.0.2 and this behavior I have only noticed when used with Mekanism-1.16.5-10.0.21.448.

**Comment by henkelmax** [comment]
This is intended behavior, as you invalidate the structure when adding a block. But after it is valid again it should connect again. But this means that the extracting state of the pipe gets lost.
Reloading the world did nothing for me.

**Comment by binare** [comment]
I am getting the same issue with both the Quantum Entangloporter as well as the Termal Evaporation Plant.  I am having the energy extraction disconnect from the Entangloporter and and the fluid extraction from the Thermal Evaporation Plant.

It seems to happen when you have a chunk with a lot of stuff in.  The Entangloporter is in the same chunk as my Refined Storage system and storage draws.

It doesn't always happen but when it does it can be a bit of a pain as I loose the pipe upgrades if I am not around and the despawn.

Would it be possible to implement a small delay before disconnecting or else have an option to lock a pipe to extract?

Thanks

**Comment by bloodscon** [comment]
yea this also happens with dank null dock if you take the dank out of the dock the pipe state resets maybe have it detect if it has an upgrade in it and if it has put a flag in place that locks the pipes state
