### ISSUE TITLE
Insane tick lag on filtering big containers

### ISSUE THREAD

**Issue by DemonMartin** [henkelmax/pipez#121]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
Connect a cable to the lowest Tier of a Filled Colossal Chest (filled with enchanted armor, mob drops, about 75% filled)
Add an Ultimate Pipe Upgrade to it and add about 20 filters to it (armor & items)
(Additional: The chest which it's piping too is full)

**Expected behavior**
The expected behavior should just be, it working fine without any problem, instead of lagging out the TPS from 20 to 11 - 13.

**Log files**
I uploaded a screenshot of the spark profiler, [here](https://prnt.sc/B1YjQf_0AVvC).
https://spark.lucko.me/NNOhh1WWyw (once the amount of items was high)
https://spark.lucko.me/oZMtUTDgP3 (when the amount got smaller and smaller)
Me trying to reproduce the problem:
https://spark.lucko.me/OTi1EbqZxt
Reproduce 2 (colossalchest filled up 90% & output chest completely full (small normal chest)):
https://spark.lucko.me/hGVjUDZSHR

**Versions**
- 1.18.2
- 18.2-40.1.30
- 1.18.2-1.1.4

**Other mods**
ColossalChests
Pipez
(In the TNP Limitless 5 Modpack, v2.8.2)

**Screenshots (Optional)**
Log Files

**Comment by henkelmax** [comment]
See #139
