### ISSUE TITLE
Unable to mine stone with wooden pickaxe

### ISSUE THREAD

**Issue by Jkesler22** [henkelmax/pipez#124]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Unable to mine stone with a wooden pickaxe while this mod is installed.  
Game version 1.19
Forge version 41.0.17
Pipez version 1.19-1.0.0

**Steps to reproduce the issue**
Start world, make wooden pickaxe, mine stone with wooden pickaxe

**Expected behavior**
Should get cobblestone, however the mining with the wooden pickaxe takes as long as though you are using your fist on stone and you do not get cobblestone...

**Versions**
Game version 1.19
Forge version 41.0.17
Pipez version 1.19-1.0.0

**Other mods**
None, only Pipez mod.
I originally started with a small list of mods but narrowed it down to this one mod through troubleshooting.

**Comment by henkelmax** [comment]
This is already fixed with #123
