### ISSUE TITLE
"Pull" mode

### ISSUE THREAD

**Issue by octylFractal** [henkelmax/pipez#125]
**Is your feature request related to a problem? Please describe.**
It's hard to set up filters for massive amounts of pipes, so e.g. when I have a lot of machines I want to only extract one specific item from, I need to go to each machine's pipe and add a filter for it.

**Describe the solution you'd like**
The ability to make a pipe _pull_ instead of _push_ things. This would allow me to add a single "pull" connection at the destination inventory, and filter on that single connection rather than on the dozens of "push" connections I currently have to modify.

**Describe alternatives you've considered**
Filtering at the destination via other means, e.g. a Storage Drawer locked to a specific item type. This introduces extra buffers and not all inventories support this filtering, such as chests.

**Comment by henkelmax** [comment]
This isn't possible due to performance reasons. The whole design of the mod is based on the extracting pipe having logic. Adding something like this would increase the complexity of the mod and would require a whole rewrite of the mod.
