### ISSUE TITLE
[1.18.2] [SMP] after server restart some pipe not connected to mekanism multiblock

### ISSUE THREAD

**Issue by ptk2003** [henkelmax/pipez#128]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
after server restart some pipe not connected to mekanism multiblock, - visually they are connected, but nothing transfert.
energy pipe to (insert) induction matrix - every server restart
fluid pipe to (insert) evaporator - every server restart
gas pipe to (insert) industrial turbine - random (~50% chanse)
gas pipe to (insert) fission reactor - random
fluid pipe to (insert) fission reactor - random
gas pipe to (insert) thermo. boiler - random

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Log files**
latest (after server boot) https://gist.github.com/ptk2003/73501d9e058e05a75e241b0c00beeab5
debug (after server boot) https://gist.github.com/ptk2003/50acaa914150e7856c0bb40f47cb75fa

**Versions**
1.18.2-forge-40.1.51
pipez-1.18.2-1.1.5

**Other mods**
Mekanism-1.18.2-10.2.3.463

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by TainanRezende** [comment]
I'm having this problem too, but in the latest version of 1.16.5, it happens not only with multblock but all machines in general, especially the gas and energy pipes, I have to remove the tip and put it back to work again

**Comment by Creepercdn** [comment]
Same problem in 1.16.5. Mekanism's multiblock will always refresh when chunk loads, and the ports of multiblock are only connectable when the multiblock is formed. So pipes will always reconnect, but Pipez does not handle/process that correctly.

And the pipes' input(pull) must be reconfigured after chunk reloads. I think Pipez must keep the pipes' input(pull) until the multiblock is formed correctly.

(Just my guess)

---
This is a critical bug. I think it should be fixed as soon as possible.

**Comment by craftingmod** [comment]
![image](https://user-images.githubusercontent.com/9389278/185771698-7fdb4e3f-711b-4488-b545-5114d8348580.png)

Mekanism multiblock can work with bypassing blockstate difference check. (With 70+ calls of dirty pipe check at once 😭 )

With enough optimizations, We can just call dirty pipe without blockstate difference check.

**Comment by craftingmod** [comment]
![image](https://user-images.githubusercontent.com/9389278/185810437-57ce0c4c-7d5e-47e9-b00b-e40d1c676ae9.png)

1. Remove equalBlockState Check and always do pipeDirty when neighborChanged

https://github.com/henkelmax/pipez/blob/7e72b00547b5158132e57eb66f536c253c4c3a4d/src/main/java/de/maxhenkel/pipez/blocks/PipeBlock.java#L318

2. Don't setConnecting false when Capability isn't available
  https://github.com/henkelmax/pipez/blob/7e72b00547b5158132e57eb66f536c253c4c3a4d/src/main/java/de/maxhenkel/pipez/blocks/tileentity/PipeTileEntity.java#L73
  
This 2 modifications should fix this issue.

**Comment by henkelmax** [comment]
If it would be that simple I would have already done it.
Changing this would mess up a whole lot of other stuff.

**Comment by Charismara** [comment]
Still happens in 1.19.2

**Comment by Chickenkarim2009** [comment]
@henkelmax 
But it should be possible to always check, if the block state changes or not? I mean how are the mekansim pipes doing it then?

**Comment by Chickenkarim2009** [comment]
> ![image](https://user-images.githubusercontent.com/9389278/185810437-57ce0c4c-7d5e-47e9-b00b-e40d1c676ae9.png)
> 
> 1. Remove equalBlockState Check and always do pipeDirty when neighborChanged
> 
> https://github.com/henkelmax/pipez/blob/7e72b00547b5158132e57eb66f536c253c4c3a4d/src/main/java/de/maxhenkel/pipez/blocks/PipeBlock.java#L318
> 
> 2. Don't setConnecting false when Capability isn't available
>    https://github.com/henkelmax/pipez/blob/7e72b00547b5158132e57eb66f536c253c4c3a4d/src/main/java/de/maxhenkel/pipez/blocks/tileentity/PipeTileEntity.java#L73
> 
> This 2 modifications should fix this issue.

Do you have a fixed version of this mod? Or at least tried out changing the code?

**Comment by TheSnowyChickens** [comment]
Any updates to this problem ?
I just destroyed my Fission Reactor with a server restart. xD

**Comment by iCloudly** [comment]
is it fixed or we need to scram reactors?

**Comment by Charismara** [comment]
afaik it's not fixed

**Comment by Chickenkarim2009** [comment]
I'm uninstalling this mod now.
The bug is nearly one year old now and still not fixed.
I understand that mod devoloping is hard, but this mod had much potential.
