### ISSUE TITLE
Incompatiblity

### ISSUE THREAD

**Issue by GamerXD8991** [henkelmax/pipez#13]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Energy pipes don't interact with mekanism and FluxNetwork

Essential desriped here: [ATM6 - To the Skys Issue Tracker](https://github.com/AllTheMods/atm6-sky/issues/48)

**Steps to reproduce the issue**
1. Place Energy Pipe
2. Place Flux Point or Plug
3. Place Energy input
3.1. See that no connection is formed on the Point / Plug (for Plug: not even when setting to Pipe to extract)
3.2. See that no connection is formed on the Universal Calbe (Pull/Push an cable doesn't cause a change)
4. Place maschine next to a Pipe
5. No energy is being transported (so it's not just a visual bug)

**Expected behavior**
Energy Pipe should connect to other mods cables/Energy Interfaces

**Log files**
No Log files

**Versions**
- MC: 1.16.5
- Forge: 36.0.46
- Modpack ATM6 - to the Skys v1.0.2
- Mod version: 1.1.2

**Other mods**
ATM6 - to the Skys Modlist
Immersive Portals
Optifine (tested without, still does not work)

**Screenshots (Optional)**
In the linked Issue

**Addions**
In Choses archtiects ATM6 Series you can see similar behavior with [RFTools Storage Cell](https://youtu.be/Na4SCQzvkLI?t=985) and [Thermals Energy Cell](https://youtu.be/Na4SCQzvkLI?t=1363).

**Comment by henkelmax** [comment]
This has already been fixed in the latest version.
