### ISSUE TITLE
Clear NBT button for filters

### ISSUE THREAD

**Issue by penturt** [henkelmax/pipez#131]
**Describe the solution you'd like**
When using a filter I know you can simply click into the NBT data field, select all, and delete all NBT data.  But, would it be possible to add a clear NBT data button on the GUI, I think such a button would make it slightly simpler for some users. 

**Additional context**
![Untitled](https://user-images.githubusercontent.com/9455895/182747617-e9b01f18-6f3b-453f-b043-9f093b5def37.png)

**Comment by craftingmod** [comment]
![image](https://user-images.githubusercontent.com/9389278/187080934-328c704e-3e2d-4759-9c29-58faa2f00ce9.png)

```java
    private Button clearNBTButton;
    public void setMaterialNBT(@Nullable String nbt) {
        if (nbt != null) {
            this.nbt.setValue(nbt);
        } else {
            this.nbt.setValue("");
        }
    }
 ```
 and
 ```java
 protected void init() {
     ...
     addRenderableWidget(item);
     
        // Clear nbt Button
        clearNBTButton = new Button(leftPos + 6, topPos + 48, 20, 20, new TextComponent("C"), button -> {
            setMaterialNBT("");
        });
        addRenderableWidget(clearNBTButton);
  ```
  
  in FilterScreen.java?

**Comment by penturt** [comment]
Yeah that would be great

**Comment by l3vines** [comment]
Having a clearer way of only moving those items that dont have an enchant would be great. 
Now if got the issue that i have broken non enchanted items in the same inventory as those that have enchants and i only want to throw away those without enchants.
