### ISSUE TITLE
Resource pack for Pipez crashes client when loaded as server resource pack

### ISSUE THREAD

**Issue by v-tron** [henkelmax/pipez#135]
**Bug description**
When loading Pretty Pipez as a server resource pack, the client crashes every time one connects to or disconnects from the server, generating the following error log:

https://pastebin.com/SrEwKpFv

I am unsure if this is an issue with Pipez or something else but the error seems to be related to the method loading the model in Pipez. Interestingly enough, when loading the resource pack manually (downloading and dropping into the folder and activating it in the client) everything works as expected.

**Steps to reproduce the issue**
1. Connect to server, accept resource pack download
2. Disconnect from server
3. Client crashes and also crashes on every subsequent connect when in resource pack loading screen

**Expected behavior**
Client doesn't crash

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- 1.18.2
- 40.1.69
- 1.1.5

**Other mods**
Part of the Direwolf20 1.18 modpack.

**Comment by henkelmax** [comment]
I can't confirm that on 1.19.2.

**Comment by henkelmax** [comment]
Closed due to inactivity.
