### ISSUE TITLE
Unable to send items to specific multiple destinations

### ISSUE THREAD

**Issue by zerofall** [henkelmax/pipez#14]
I am extracting multiple types of items from 1 location, and I would like to send specific items to specific destinations (multiple). I am able to use the filter destination tool to specify locations, but no matter what combination of whitelist/blacklist/inverted I use, items either go to the first available inventory, or don't get extracted at all. Is this a bug? If it is user error, can you help me understand how to achieve this?

![image](https://user-images.githubusercontent.com/12579976/112402710-05533e00-8cdb-11eb-9a7a-45fcef6eb971.png)

**Comment by henkelmax** [comment]
You are using the sorting mode `Nearest First` you have to use `Round Robin` for that.

**Comment by zerofall** [comment]
Hmm, that would imply that "Nearest First" ignores the whitelist, but "Round Robin" respects the whitelist. If that is true, it's definitely not obvious.

**Comment by henkelmax** [comment]
No, but whitelists just apply for the destination that is set.

**Comment by jelaw21** [comment]
I had this issue at first. Had a chest with extraction and upgraded it to a basic. Then up to advanced. Filtering didn't work. I broke the chest and pipe and replaced, filtering worked.
