### ISSUE TITLE
Filtering is broken / no integration with Trash Cans mod

### ISSUE THREAD

**Issue by toolongtospell** [henkelmax/pipez#141]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Item pipe upgraded with Adv. Upgrade is not enforcing the whitelist filter and is allowing all items to flow to the Item Trash Can.

**Steps to reproduce the issue**
1. Add Advanced Pipe Upgrade
2. Open Pipe config by right-clicking on the pipe coming from the source chest.
3. Change Filter to 'Whitelist' mode
4. Click on Add
5. Shift-Click or Drag the item into the filter slot (item type doesn't matter)
6. Use the destination tool to set a destination.
7. Click 'Submit'
8. Connect the source chest to the 'Item Trash Can' (Trash Cans mod)
9. All items from the source chest flow into the trash can despite the filter.

**Expected behavior**
Expect the filter to only allow whitelisted items through the pipe.
 
 --- NOTE ---
When replicating the steps above but replacing the Item Trash Can with a destination chest the filtering works.

**Versions**
- Minecraft version - 1.18.2
- Forge version - 40.1.74
- Mod version - 1.15

**Other mods**
Trash Cans mod

**Screenshots (Optional)**

**Comment by henkelmax** [comment]
Filters with a specific destination only apply for that destination.
This completely works as intended.

**Comment by toolongtospell** [comment]
Just so I understand, does setting a destination overwrites the whitelist?

**Comment by henkelmax** [comment]
No. Filters just only apply for that exact destination. If you want it to not go into another inventory, you need to blacklist it for that destination.

**Comment by toolongtospell** [comment]
Okay, thank you for the information and I'll do some more testing to help educate myself on your mod.
