### ISSUE TITLE
[1.18.2] Fluid Pipes Connecting to Cauldrons

### ISSUE THREAD

**Issue by MokahTGS** [henkelmax/pipez#143]
**Is your feature request related to a problem? Please describe.**
Currently Pipez don't connect to cauldrons making a cheap and effective lava farm impossible with the new dripstone mechanics.

**Describe the solution you'd like**
Please allow fluid pipes to connect to cauldrons to pull liquid out or push liquid in.

**Comment by henkelmax** [comment]
Duplicate of #93
