### ISSUE TITLE
Pipez should retain pull configuration

### ISSUE THREAD

**Issue by Zhirsh** [henkelmax/pipez#144]
Pipes do not keep their pull configuration when what they are attached to is removed.

Have them retain what they were configured as using the wrench (ie instead of defaulting to receive w
hen the pull item is removed)

Using the wrench to re-config them when the pull block is returned. Aside from this no other alternative has been found as yet.

**Comment by henkelmax** [comment]
Pipes can't carry any data when not connected for performance reasons.
