### ISSUE TITLE
Pipes not respecting filter destination 

### ISSUE THREAD

**Issue by Juh-Kobe** [henkelmax/pipez#146]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
It Appears Pipes are not respecting the filter destination tag when trying to export to mechanical belts(Create Mod)

**Steps to reproduce the issue**
1. Set up a pipe network when connecting to multiple mechanical belts
![image](https://user-images.githubusercontent.com/78878221/195740545-366bf2d5-57d7-44ff-933c-f306bd03e799.png)
3. Set the destination with the destination tool and put it into the filter 
4. 
![image](https://user-images.githubusercontent.com/78878221/195740707-00aa9e33-ece7-4c61-a51b-abf5044ffbf3.png)
![image](https://user-images.githubusercontent.com/78878221/195740797-be640a73-a6a7-4be0-9014-a073a85b709b.png)

5. check items at the destination
7. See error
8. 
![image](https://user-images.githubusercontent.com/78878221/195740880-8f1547b8-2f88-4a1d-9a51-66f99c951294.png)

**Expected behavior**
Items should be going to the one on the far right in the pictures. The second one x is 276 and not 274

**Log files**
Which log? "Latest.log"?
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version - 1.18.2
- Forge version - 40.1.80
- Mod version - 1.18.2-1.1.5

**Other mods**
Using with All the Mods 7 - Version 0.4.32

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
This is conpletely intended. Filters only apply for the destination you configured them for. They won't stop the items from going anywhere else.

**Comment by Juh-Kobe** [comment]
So I configured the iron essence to go to destination 1, yet it is going to destination 2. This is intended?  I have other filters in other pipe networks in my world and non of them work that way

**Comment by Juh-Kobe** [comment]
I added other filters to it and now it's working, Iron is only going to the first one, gold is going to the second one and netherite is going to the third and not going anywhere else.
I think I understand what you mean by working as intended

Thank you for the quick response
