### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by ZornTaov** [henkelmax/pipez#147]
**Is your feature request related to a problem? Please describe.**
Add a License to your github code.  One only exists for your CurseForge mods page.

**Describe the solution you'd like**
Pick one, you can do it directly on github's website by adding a new file named LICENSE and picking one.

**Describe alternatives you've considered**
Depending how open you are to others using parts of your code, or making addons or the like, maybe MIT?

**Additional context**
I'm re-making my EnergyNodes mod and was about to base my code on your `EnergyPipeType.insertEqually` method as it looked cleaner than my previous attempt at distributing energy.

**Comment by henkelmax** [comment]
If you don't specify a license on github its all rights reserved by default.
You can also see the license on curseforge.
