### ISSUE TITLE
Default to "Always Disable" when configuring gasket

### ISSUE THREAD

**Issue by shanoaice** [henkelmax/pipez#149]
**Is your feature request related to a problem? Please describe.**
When the pulling function of a pipe connection is enabled, all of its extraction redstone sensitivity is set to "Ignore", which can sometimes cause contents to be transported to non-desired locations (such as accidentally pumping oxygen into machines that were meant to make Hydrochloric Acid)

**Describe the solution you'd like**
When a connection is set to extract, the redstone sensitivity could be default to "Always Disable" for players to correctly configures filters and destination.

**Describe alternatives you've considered**
_None._

**Additional context**
_None._

**Comment by henkelmax** [comment]
Changing the redstone mode needs an upgrade. If the redstone mode would be ignore by default you wouldn't be able to use pipes without upgrades.
