### ISSUE TITLE
Incompatibility with Thermal Redstone Flux Cell

### ISSUE THREAD

**Issue by TheDarkPreacher** [henkelmax/pipez#15]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Energy pipe will not extract from side of Thermal cell that is set to extract, but will insert power just fine on side set to insert.

**Steps to reproduce the issue**
1. Place Thermal cell, one side set to export power
2. place energy pipe, use wrench to set to extract from cell
3. attach other end of energy pipe to energy using block
4. Notice that there is no energy being extracted from cell.

**Expected behavior**
I expect an energy pipe set to extract to extract energy from a Thermal energy cell set to export.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.0.46
- Mod version: Pipez v. 1.16.5-1.1.2, Thermal 1.16.5-1.2.0

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.
Cell set to export, pipe set to extract, hooked into energy trash can.
![image](https://user-images.githubusercontent.com/15058826/112445010-aa423b00-8d1c-11eb-9295-f4c61104ffe9.png)
Internal config of cell, set to export.
![image](https://user-images.githubusercontent.com/15058826/112445057-ba5a1a80-8d1c-11eb-870a-5e719ee52f37.png)

**Comment by henkelmax** [comment]
Basically the same as #7 and #6
