### ISSUE TITLE
Feature request: Pipez to connect to Vanilla MC Cauldrons

### ISSUE THREAD

**Issue by ryu2065** [henkelmax/pipez#153]
I would like to suggest a feature request for this amazing mod. 

I would like fluid pipez to connect to Vanilla MC Cauldrons. Currently there is only the option using buckets by hand or a Create mechanical pump to extract fluid from them. 

I know this is a very niche request, but its one that I feel is a quality of life upgrade.

Thank you for your time.
-Ryu2065

**Comment by henkelmax** [comment]
Duplicate of #93
