### ISSUE TITLE
there is not config file

### ISSUE THREAD

**Issue by SharkBairRFSR** [henkelmax/pipez#155]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version
- Forge version
- Mod version

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

I am looking for the config file and it doesn't seem to exist, Id like to unlock the infinite upgrade but i cant edit a config that doesn't exist

**Comment by henkelmax** [comment]
Please properly fill out the bug template
