### ISSUE TITLE
There is no config file

### ISSUE THREAD

**Issue by SharkBairRFSR** [henkelmax/pipez#156]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
I am looking for the config file and it doesn't seem to exist, Id like to unlock the infinite upgrade but i cant edit a config that doesn't exist

**Steps to reproduce the issue**
1. Go to '...' config
2. Click on '...' nothing it doesn't exist
3. Scroll down to '...' p look for pipez it doesn't exist
4. See error pipez config doesn't exist

**Expected behavior**
I expect to scroll to the ps in config and see a pipez config file

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).
won't really help i don't think

**Versions**
- Minecraft version 1.19.2
- Forge version 43.1.52
- Mod version 1.0.1

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
tested it with only pipez mod and continues

**Screenshots (Optional)**
Screenshots of the issue.
![pipezmods](https://user-images.githubusercontent.com/91989416/202861719-01e4803f-d6cc-4aa7-979f-3dee33377533.JPG)

![pipezconfig](https://user-images.githubusercontent.com/91989416/202861715-9093c2c4-73e9-4d4e-add4-2a2e5afafa33.JPG)

**Comment by henkelmax** [comment]
This is not a bug. The config is located in your world folder in /serverconfig
