### ISSUE TITLE
Problems with filters

### ISSUE THREAD

**Issue by ZEkA10000** [henkelmax/pipez#157]
I use combination of few mods (own local modpack)

I have 11 types of **Ore pieces** _(Ex Nihilo:Sequentia + Ex Compressum)_ and 11 **Drawers** _(Storage Drawers mod)_
I set with filter destination tool all 11 ores to 11 drawers from one chest. 
It worked normally, but when drawers are empty pipe move more items _not listed_ in filter (Used whitelist mode)

How to stop moving items (coal, flint, diamond) when filter have only _ore pieces_?

Minecraft 1.16.5

**Comment by henkelmax** [comment]
When a destination is set, the filter only applies to the destination specified. It can still go through other connections.

**Comment by ZEkA10000** [comment]
That means I need to use 11 filters for one item, right?

**Comment by henkelmax** [comment]
No. You can invert the whole extractor.
