### ISSUE TITLE
[BUG] Pipez don't connect to Vanilla composters

### ISSUE THREAD

**Issue by RyanWBell** [henkelmax/pipez#161]
**Bug description**
Pipez do not connect / see composters as valid entity blocks that they can interact with.

**Steps to reproduce the issue**
1. Place composter
2. Place item pipe adjacent to composter
3. Try and use pipe wrench and no connection is viable

**Expected behavior**
Pipe connects to composter and can input items and extract bone meal

**Log files**
N/A

**Versions**
- Minecraft version : 1.18.2
- Forge version : 40.1.61
- Mod version: pipez-1.18.2-1.1.5.jar

**Other mods**
Vault hunters alpha 0.0.3h (These are not causing the issue though)

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/18196106/207736678-381fbd32-f6b3-476e-b827-c4158dd2fdfe.png)

**Comment by RyanWBell** [comment]
I'm confused, it's not intended for pipez to connect to a tile entity that has an inventory? So it can connect to tons of machines, chests, and even things like item frames / spice racks, but composters is a deliberate choice of non-integration? 

Would you like me to reopen this ticket as an enhancement?

**Comment by henkelmax** [comment]
The composter is not a tile entity and thus won't connect.
