### ISSUE TITLE
Editing NBT Data filtering does not save when using keyboard shortcuts 

### ISSUE THREAD

**Issue by Gyousei** [henkelmax/pipez#164]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report! (just an FYI this is a broken link)**

**Bug description**
When deleting NBT data from a filter entry on an exporting item pipe, if the NBT is deleted by selecting it with ctrl + a -> backspace, the changes to the NBT are not saved, however, deleting it by holding backspace (which can take a while for items with many NBT flags) saves it normally after hitting submit. I discovered this bug while playing the Ragnamod VI modpack, and then found that it occurred even with this version of pipez installed on its own. This isn't a huge issue in functionality, but it's very time consuming to work around.

**Steps to reproduce the issue**
1. Have an Item pipe (not applicable to fluid/energy) extracting items from an inventory using an ultimate pipe upgrade
2. Add an item filter using an item that currently has one or more NBT tags
3. Delete the NBT tags (so as to filter all items of that type, regardless of NBT) by hitting ctrl + a -> backspace
4. Click Submit

**Expected behavior**
The filter entry will no longer possess any saved NBT data

**Log files**
I can provide more logs if needed, but I've looked through them thoroughly and don't see any abnormal logs pertaining to the pipez mod. I've attached my latest.log after experimenting with the bug in single player
[latest.log](https://github.com/henkelmax/pipez/files/10367175/latest.log)

**Versions**
- Minecraft version: 1.16.5
- Forge version: Forge 36.2.39
- Mod version: pipez-1.16.5-1.2.15

**Other mods**
Occurs with only the following installed
Forge 36.2.39
Pipez 1.2.15

**Screenshots (Optional)**
I've uploaded a video of the behavior on youtube [here](https://www.youtube.com/watch?v=ntxkidp7VOA)
This video was recorded from within the ragnamod modpack, however, the log file attached is the one from the installation with only forge and the pipez mod.

**Comment by henkelmax** [comment]
Doesn't happen in 1.19.2+ anymore
