### ISSUE TITLE
How does whitelist works exactly?

### ISSUE THREAD

**Issue by lyssar** [henkelmax/pipez#17]
I have an issue where
I have a source chest (which is in this case the drawer slave from the drawers mod) with N diffrent items.
I have  2 destination chests, 1 ender chest from "EnderChests" mod and 1 normal minecraft chest

What I want to:
The minecraft chest should only recieve cobblestone but nothing else buuut I cant get it to work with a 
 
But in my destination chest I get  just plain every item from the source, why is that?
  
Filter Overview:
![source_pipez_filter](https://user-images.githubusercontent.com/814001/112770831-e8936f00-9028-11eb-84ee-80c603c716f9.png)

Filter for the Chest:
![filter](https://user-images.githubusercontent.com/814001/112770836-ed582300-9028-11eb-991c-2f8f7e5f97ed.png)

Destination chest outcome:
![destination_chest](https://user-images.githubusercontent.com/814001/112770837-efba7d00-9028-11eb-8b60-26a8203e58c2.png)

**Comment by henkelmax** [comment]
A whitelist applies only for the destination you set it for.
If you want your item to only get into that destination you either need to make a blacklist for the other destinations or create a whitelist with other items for all other destinations.
Another way to do it would be to use an intermediate chest for all other items.

I know this seems a bit counter intuitive at first, but it allows for very specific and complicated setups.

**Comment by lyssar** [comment]
This doesn't explain why in my destination chest are all items instead of just cobblestone.
I would asume that when I am saying: Filter for cobblestone in destination that only cobblestone will be in my destination instead of just all items which are present in my source.

**Comment by henkelmax** [comment]
Maybe you clicked on the wrong face with the destination tool.

**Comment by lyssar** [comment]
thnx for you help. :) had the wrong face used.
