### ISSUE TITLE
Fluid pipe

### ISSUE THREAD

**Issue by iCloudly** [henkelmax/pipez#173]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/pipez/faq)!**

There is a problem with fluid pipe with infinity upgrade. When i join my world , pipe doesnt work even if it look like its working and  extracting. I have Mekanism fission reactor multiblock that requires 36 milion milibuckets of water per tick and if it there is no input of water reactor almost instantly explodes and realesing radiation. Is that a bug or what.

**Comment by henkelmax** [comment]
#128
