### ISSUE TITLE
Item Pipes don't work with Mod Botany Pots

### ISSUE THREAD

**Issue by Mazimations** [henkelmax/pipez#175]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
1. Get a botany pot and place down high enough to reach underneath
2. Place item pipe underneath
3. Attempt to use the wrench
4. Wrench or not, it won't connect

**Expected behavior**
The item pipes should connect to the botany pots like any other storage entity such as a chest with it's own inventory, however, it does not.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.19.3
- Forge version 44.1.23
- Mod version pipez-1.19.3-1.0.3.jar

**Other mods**
Botany Pots
Botany Trees

**Screenshots (Optional)**
Screenshots of the issue.
![2023-04-06_18 41 12](https://user-images.githubusercontent.com/60023204/230506952-cf1a77b4-058c-4bbf-8717-0dc23057a794.png)

**Comment by henkelmax** [comment]
Botany pots don't have an inventory. Its not possible to pull from it. You need to place a container below in order for it to output items.

**Comment by henkelmax** [comment]
Oh, did that change?
I remember it not working even with mekanisms pipes in 1.16.5

**Comment by Darkhax** [comment]
Yeah, in 1.16.5 the pot didn't have an inventory or buffer at all, but that was changed a long time ago.

**Comment by Daniel-ags** [comment]
Okay, so out of curiosity, the mod itslef needs a new version? Or is it something that u can like, patch into the latest version?
@henkelmax

**Comment by Darkhax** [comment]
It seems to work fine for me. 
![image](https://github.com/henkelmax/pipez/assets/2250798/111646f5-63a1-41d9-84df-2ee12bc341d7)

**Comment by henkelmax** [comment]
Same. Works perfectly fine.

![image](https://github.com/henkelmax/pipez/assets/13237524/cb7fdeb9-3b8f-49a0-baa0-24a07e08804b)

**Comment by Daniel-ags** [comment]
Okay. I'll try a brand new installation to look for any problems. Thanks for the support!
