### ISSUE TITLE
Can we filter by item category or RegEx?

### ISSUE THREAD

**Issue by katieisnell** [henkelmax/pipez#176]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/pipez/faq)!**

In my use case, I would like to have a filter that sends all types of logs to one chest, and all types of planks to another chest, etc. What is the best way to do this with the current filter?

My current thinking is I need to add a filter for every item ID which, whilst possible, will take a long time for my whole setup (so I would like to avoid it if possible).

Bonus question: can we add multiple item IDs to one filter?

**Comment by henkelmax** [comment]
You can invert filters. What you need to do is create a filter for every destination the pipe goes to.

**Comment by katieisnell** [comment]
> You can invert filters. What you need to do is create a filter for every destination the pipe goes to.

So for example if I had x chests and I wanted logs to go into chest 1, planks to go into chest 2, and other filters for the other chests, would so need to add invert filters to every single chest except chest 1 and 2?

**Comment by henkelmax** [comment]
I think you could do that by inverting all filters and then adding blacklisted filters with the destination
