### ISSUE TITLE
Named Pipez

### ISSUE THREAD

**Issue by lyssar** [henkelmax/pipez#18]
I use your pipez quite a lot in ATM6 now and I came across an little overview issue :D 
So I have now a lot of item pipez  and no clue which one is which after a time. 

What I would like to have now is a possibility to either add a nametag for the pipe (giving a stack of pipez a name with the anvil doesn't work)  or be able to color them with dye to get them organized better.

Regards,
lyssar

**Comment by lyssar** [comment]
Any thought on this so far? :) a month til posting - was wondering about that topic

**Comment by henkelmax** [comment]
I am currently focusing on getting all bugs fixed before adding new features.

**Comment by henkelmax** [comment]
Unfortunately this is not possible, since inserting(non extracting) pipes don't have block entities and thus can't have names.
A feature like you suggested is technically already a thing, since you can for example rename a chest in an anvil and it would show that name in the filter destination.
