### ISSUE TITLE
Am i doing something wrong?

### ISSUE THREAD

**Issue by Daniel-ags** [henkelmax/pipez#181]
![image](https://github.com/henkelmax/pipez/assets/53279612/a1a9612a-071d-4634-b8a1-ccfbb0bf7ee0)

I made sure to use *hopper* botany pots and to connect to a terminal inventory, but it doesn't even connect. I tried changing the pipez and botany pots mod version to all the 1.19.2 versions available and still nothing.

![image](https://github.com/henkelmax/pipez/assets/53279612/e77866b0-a1f5-4418-9c24-d5a4e44ba0f9)

(The red botany pot is also a hoping one. The hopper texture is in the inside of it)

**Comment by henkelmax** [comment]
#175

**Comment by Daniel-ags** [comment]
Okay, understood that part, but why when i play on a server they connect?

![image](https://github.com/henkelmax/pipez/assets/53279612/b78a04e2-0d4b-4b3a-b4c4-fb66960b67c4)

Do they have inventory or a internal buffer of some sort when on a server? I really like the functionality they have with botany pots.

Also, in the video that i'll link, u can see right at the beginning the pipez connecting to the Pots. 

https://www.youtube.com/watch?v=BFyxjeW_18Y
