### ISSUE TITLE
Configuring Pipez for Server Usage: Modifying Limits for Pipe Upgrades

### ISSUE THREAD

**Issue by WarrenN1** [henkelmax/pipez#183]
I am trying to custom configure Pipez for the server to be able to handle some of the mekanism machines. The upgrade thresholds are too low. I am on 1.18.2 and can't find a .conf file for it.

For context within minecraft/config/ I cannot find any Pipez configuration file for these limits.

**Comment by henkelmax** [comment]
https://modrepo.de/minecraft/faq

**Comment by WarrenN1** [comment]
It is not located there as I checked that FAQ first. There is no PIPEZ folder or PIPEZ toml.

**Comment by henkelmax** [comment]
Where exactly did you look?

**Comment by WarrenN1** [comment]
Within minecraft/config/* (see initial message). Couldn't find the .toml or folder for it for version 1.18.2

**Comment by henkelmax** [comment]
Yeah. You clearly didn't read the FAQ. The path is `<world>/serverconfig/pipez-server.toml`.

**Comment by WarrenN1** [comment]
Is there a way to configure it server wide though to run at a specific rate not world by world?
