### ISSUE TITLE
Massive lag with rate-limiting fluid handlers

### ISSUE THREAD

**Issue by Technici4n** [henkelmax/pipez#184]
Hi, in AE2 we have set up a rate limit for the Matter Condenser, meaning that it will only accept 1000 mb of fluid at a time. Pipez is I believe trying to perform `Integer.MAX_VALUE / 1000` insertions, which is causing quite some lag: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7140. We'll implement a workaround, but it would be nice if you had a limit on the number of iterations to preserve sanity.

(Another even better fix would be to not try inserting multiple times in the same fluid handler as that will just bypass any intentional rate limit, but I leave that choice to you).

**Comment by henkelmax** [comment]
> Pipez is I believe trying to perform Integer.MAX_VALUE / 1000 insertions

This would only be true for the infinite upgrade which isn't craftable.

**Comment by Technici4n** [comment]
Modpacks often make infinite/creative stuff craftable I guess.

**Comment by henkelmax** [comment]
They are uncraftable for a reason. Having infinite transfer speeds is very laggy in a lot of cases.

**Comment by robotgryphon** [comment]
That won't work with a lot of players; they see it in the game, they'll ask "but why can't I use it, it's THERE"

**Comment by henkelmax** [comment]
Then you need to live with the lag. Theres nothing that can be done about that.
