### ISSUE TITLE
Nbt Filter Doesn't Work With Apotheosis Armor

### ISSUE THREAD

**Issue by Cyranos** [henkelmax/pipez#186]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**

When using apotheosis you are able to filter apotheosis gems by rarity though the same can not be said about armors

**Steps to reproduce the issue**

1. Using either the ultimate pipe or the normal item pipe connect it between two chests
2. Mark one side as an extraction & add a filter
3. Add "#forge:armors" too the Item/Tag field
4. Add "{rarity:"rare"}" too the NBT Data field

**Expected behavior**

For the armor to be filter like the gems are, where for the gems I just have "apotheosis:gem" for the Item/Tag field & "{rarity:"rare"}" in the NBT Data field it will only take gems that have the "rare" nbt tag

**Log files**
No log info found about this

**Versions**
- Minecraft version : 1.19.2
- Forge version : 43.2.14
- Mod version : 1.1.0

**Other mods**
JEI Version : 11.6.0.1015
Apotheosis Version : 6.2.1
Placebo Version : 7.2.0

A shortish video on what I am meaning to hopefully make sure I didn't mess up explaining anything
https://youtu.be/dy8GyZbwdkQ

**Comment by Cyranos** [comment]
An update is this issues part take to anything that is not apotheosis gems, like tool, weapons, etc

**Comment by logixcraft** [comment]
I'm experiencing the same issue and it persists even if I load the base ATM9 pack and try it there.

**Comment by BarenZ2** [comment]
Hello Guys, 
I know how to fix it, but I dont know how it works exactly.
I found this in a youtube video and it works for me (newest version of ATM 9)

Item tag: #forge:armor
NBT Data: {affix_data:{rarity:"apotheosis:rare"},apoth_rspawn:1b}

Item tag: #forge:tools
NBT Data: {affix_data:{rarity:"apotheosis:rare"},apoth_rspawn:1b}

Change out rare for epic or mythic!!!
