### ISSUE TITLE
Only 2/3 NBT Filtering Options Available

### ISSUE THREAD

**Issue by ArcTrooper210** [henkelmax/pipez#187]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/pipez/faq)!**
FAQ link is dead just a heads up.

With the advanced upgrade, I can only select "Match only provided tags" and "Match exact NBT data" but there is no option for "Match none" as stated in the mod description. I'm using pipez 1.19.2-1.1.0 included in the 1.0.19b All the Mods 8 modpack. I checked config options but there are no config files in the config folder and the ingame config only let's you adjust amount of items/energy/gas/fluid per tick for the pipes.

**Comment by henkelmax** [comment]
Just delete the NBT string
