### ISSUE TITLE
limited item filter

### ISSUE THREAD

**Issue by bloodscon** [henkelmax/pipez#19]
Any chance of the high tier filter having a limiter on it so you can limit how many it puts in the chest
so say default limit mode set to say 32 and you send sand and cobble to a chest the chest will end up with 32 cobble and 32 sand
but if you use filter mode you can even adjust the item stack so you could have 20 cobble and 10 sand

**Comment by henkelmax** [comment]
I don't think this is too useful. It would just add more complexity to the UI

**Comment by TheDarkFlame** [comment]
sorry to necro, wanted to ask for this too...

I think the most likely use-case for this is automating a blood altar, or the energizing orb from powah, etc. 
The attached inventory allows for many more items, but if multiple items are inserted, crafting does not proceed.
