### ISSUE TITLE
[1.20.1] Pipes not accepting input from more than 2 sources in 1 block

### ISSUE THREAD

**Issue by markaabo** [henkelmax/pipez#196]
**Bug description**
As the title says if you connect 1 pipe to 2 sources it will not extract gas from all sources even when the first source is empty

**Steps to reproduce the issue**
1. Place 2 Electrolytic Separator on either side of a pipe
2. Connect the pipes to the 2 machines and use wrench to make them extract from them (Be sure the machines are set to output gas to the side you connected to the pipe)
3. Turn on machines

**Expected behavior**
All sources should be able to provide pipes with gas

**Log files**
No logs since its not a crash

**Versions**
- Minecraft version: 1.20.1
- Forge version: 1.20.1-47-1-43
- Mod version: 1.1.4
- Mekanism: Mekanism-1.20.1-10.3.9.homebaked-all

**Screenshots (Optional)**
![2023-08-16_15 01 52](https://github.com/henkelmax/pipez/assets/68380434/698a10b9-b1d8-47a6-b3d3-e4a2985a2717)

**Comment by henkelmax** [comment]
Did you connect the pipe to a destination?

**Comment by markaabo** [comment]
> Did you connect the pipe to a destination?

Yes their connected to 3 mekanism infusers

**Comment by henkelmax** [comment]
You are using 1.20.1. Mekanism is not yet officially released for that version.

**Comment by markaabo** [comment]
@henkelmax i have just found that this also happens with Item pipes, and normal vanilla chests, so its not mekanism related

**Comment by markaabo** [comment]
This happens with or without upgrades installed in extracting side

Heres proof:
![2023-08-19_18 34 03 - Copy](https://github.com/henkelmax/pipez/assets/68380434/c23caff4-bc7a-4272-bcfe-a79ee0f48d61)
![2023-08-19_18 33 50](https://github.com/henkelmax/pipez/assets/68380434/7da5f97d-5dcc-4dfa-8061-4bb634660b0b)
![2023-08-19_18 33 53](https://github.com/henkelmax/pipez/assets/68380434/1c08d962-d3c5-4caf-81ea-a5dc4405c49f)

**Comment by henkelmax** [comment]
Did you set any filters or destinations?

**Comment by markaabo** [comment]
> Did you set any filters or destinations?

Nope in the screen shots its litterally just extract pipes with no upgrades and no nothing, and even if i add upgrades it does not work

**Comment by henkelmax** [comment]
Not sure if you understand how the mod works, but there are a lot more inserting connections. The mod chooses the shortest path by default.
![image](https://github.com/henkelmax/pipez/assets/13237524/d092b575-b441-4975-a3c6-b5e4dee8c0f8)

**Comment by markaabo** [comment]
> Not sure if you understand how the mod works, but there are a lot more inserting connections. The mod chooses the shortest path by default. ![image](https://user-images.githubusercontent.com/13237524/261838899-d092b575-b441-4975-a3c6-b5e4dee8c0f8.png)

I know how it works, but even where it moves the items to which is the shortes it *never* pulls from the right chest. here let me make a completely cardboard cut version so you can see what the problem is:

A and B are chests filled with items
C is the out put chest

When setting this style of "2 source connections pipe" up the pipe will *NEVER* pull any items or gas (after pipe type and machine) even when 1 of the chests/machines are empty, it seems that the first "side" you change to extract is the side that actually works, and the secound 3 or 4 connection set to extract never extracts from the chest or machine, you need to disconnect the side you connected first and reconnect the side which was set to extract after the first one.
![2023-08-20_13 12 54 - Copy](https://github.com/henkelmax/pipez/assets/68380434/27a4c290-8883-425f-992b-da8b77c6514c)


Note: i have found that doing this with item pipes seem to work some times but not all, seems to happend randomly and not depend on oriantation, though when doing it with gas pipes (which you say are for mekanism) it never works and will always only extract from 1 machine

**Comment by henkelmax** [comment]
Ok, now I understand the issue, thank you for providing a simple example!
