### ISSUE TITLE
Error: CCL Caught and exception rendering a block

### ISSUE THREAD

**Issue by papaworld** [henkelmax/pipez#2]
MC    1.16.5
FML   35.0.42
Pipez  pipez-1.16.5-1.0.10

Note: this error did not occur with FML 35.0.26 and pipez-1.16.5-1.0.9

Existing World load and running this error appeared in the in-game command dialog. Went in to Creative and Gave 64 of each pipe type. Again the error appeared. Here's what Gave displayed in the dialog:

CCL Caught an exception rendering a block. See the log for info.
Gave 64   {blank no pix of pipe}   [Item Pipe] to "player"
Gave 64   {pix of Item Pipe}         [Fluid Pipe] to "player"
Gave 64   {pix of Fluid Pipe}         [Energy Pipe] to "player"
Gave 64   {pix of Energy Pipe}     [Gas Pipe] to "player"
CCL Caug{pix of Gas Pipe behind letters}ht an exception rendering a block. See the log for info.

Placing the pipez in the world... they functioned correctly without error notification. If you want the "log" file... let me know which one "latest" or "debug".

Also, Gave properly rendered all 5 Upgrades, Wrench and Filter Destination Tool.

Nice mod. It seems to work in the same manner as Ender I/O conduits... meaning the pipes are only source to target without anything actually being "in" them. Would this be correct?

Possible to add a Redstone Pipe to your mod?

Thank you.

**Comment by henkelmax** [comment]
> If you want the "log" file... let me know which one "latest" or "debug".

I need the `debug.log` file, but the `latest.log` would also work.

Does this issue also occur without any other mods installed? If not, please find out what mod it is.

> Nice mod. It seems to work in the same manner as Ender I/O conduits... meaning the pipes are only source to target without anything actually being "in" them. Would this be correct?

Exactly, except that all pipes that are not extracting contain no block entities, to minimize the performance impact.

> Possible to add a Redstone Pipe to your mod?

We thought of this too. We might add this some time in the future.

**Comment by papaworld** [comment]
Here's the debug log.
I will check to see if it occurs with only the pipez mod.
Oh my, I've got 260+ mods installed, to find out which one may be an issue would be a bit of a task.
Mods installed that use pipe/conduit: Mekanism, Pretty Pipes, Refined Pipes, Refined Storage, Large Fluid Tanks, Cyclic... I'm sure that's not all of 'em.

[debug.log](https://github.com/henkelmax/pipez/files/5994397/debug.log)

**Comment by henkelmax** [comment]
From what I can see with the logs, you could try removing refined storage and the code chicken lib first.

**Comment by henkelmax** [comment]
Closed due to inactivity
