### ISSUE TITLE
Pipez + Flux Networks are not working

### ISSUE THREAD

**Issue by LuziferSenpai** [henkelmax/pipez#20]
Hey,

I tried to extract and input power from/into my Flux Network via Pipez, but they dont seem to like it.

<img width="1920" alt="javaw_Wqux1LHQh0" src="https://user-images.githubusercontent.com/38015859/113266268-62e81b80-92d5-11eb-93f4-3d2f69b0fde1.png">

<img width="1920" alt="javaw_jjGU4q6XAB" src="https://user-images.githubusercontent.com/38015859/113266485-9fb41280-92d5-11eb-832a-38441815d9dd.png">

**Comment by henkelmax** [comment]
Please fill out the complete bug template. Also make sure that you tested it with the latest version of the mod.

**Comment by LuziferSenpai** [comment]
Version 1.16.5
Forge 36.1.2
Mod Version: 1.1.5

Mod Pack: ATM Skyblock

Flux Networks Version: 6.1.6.11

Expected bevahiour: Connect and provide/get power.

Reproduce:
1. Place a Flux Network Point/Plug
2. Select a Network
3. Place a Pipez Energy Pipe
4. Set it to extract or just let it be.

And I dont think you need logs, because it doesnt crash, it just dont work together currently.

**Comment by henkelmax** [comment]
You are not using the latest version. Please use the latest version of the mod.

**Comment by LuziferSenpai** [comment]
I'm using the latest version avaible on Curse.

**Comment by henkelmax** [comment]
https://www.curseforge.com/minecraft/mc-mods/pipez/files/3254516

Clearly not.

**Comment by LuziferSenpai** [comment]
Okay, Point seems to work now, but Plug still doesnt accept the power from the cables.

**Comment by henkelmax** [comment]
It tested it and it seems that the Flux Plug does not connect if there is no energy capability on the block next to it.
Due to the implementation of the Pipez mod it is not possible to fix it from our side.
You have to report that to the Flux Networks issue tracker.
