### ISSUE TITLE
Upgrade duplications

### ISSUE THREAD

**Issue by ZEkA10000** [henkelmax/pipez#209]
**Bug description**
I don't know are you still support your mod for 1.16.5 but I found a bug where I can dup upgrades with using Cyclic mod

**Steps to reproduce the issue**
1. Craft Sack of Holding from Cyclic
2. Craft at least one upgrade
3. Place storage block (e.g. chest or barrel)
4. Connect pipe to storage block
5. Insert upgrade
6. Use Sack of Holding on pipe
7. Upgrade will dropped because Pipe disconnected/destroyed but pipe with that upgrade already in that Sack of Holding

![javaw (2023-Ноябрь-25 14_01_25)](https://github.com/henkelmax/pipez/assets/25690631/70acfc2b-d31d-421d-ac48-ebcfddd90f90)

**Versions**
- Minecraft v1.16.5
- Forge v36.2.22
- Pipez v1.16.5-1.2.7

**Other mods**
I already described that dup with Cyclic mod (1.16.5-1.5.12)

**Comment by henkelmax** [comment]
I'm sorry, but that version is no longer actively supported. You might also want to report this to cyclic or blacklist that block. It is not recommended to copy pipe block entities, as they are dependent on their locations and connections.
