### ISSUE TITLE
Can't transport Items into Mekanism Bins and Industrial Foregoing Black Hole Units.

### ISSUE THREAD

**Issue by Javahase** [henkelmax/pipez#21]
**Bug description**
Can't transport Items into Mekanism Bins and Industrial Foregoing Black Hole Units.

**Steps to reproduce the issue**
1. Connect Universal Pipe (or Item Pipe) to a Container containing some items.
2. Connect Universal Pipe (or Item Pipe) to a Black Hole Unit or a Mekanism Bin.
3. See how it won't insert anything at all.

**Expected behavior**
I expected that the Pipes would insert the Item into the Black Hole Unit/Mekanism Bin but they didn't. They just kept staying in the Container containing those items.

**Log files**
There are no Log files needed.

**Versions**
- Minecraft version: 1.16.5
- Forge version: forge-36.1.2
- Mod version: 1.16.5-1.2.1

**Other mods**
- Industrial Foregoing
- Mekanism

**Screenshots (Optional)**
/

**Comment by henkelmax** [comment]
![2021-04-05_17 32 54](https://user-images.githubusercontent.com/13237524/113592130-0b2f1480-9635-11eb-9832-ee99d85c42c2.png)
![2021-04-05_17 33 17](https://user-images.githubusercontent.com/13237524/113592134-0cf8d800-9635-11eb-86d9-ef49a20e9f6b.png)

Works perfectly fine.

**Comment by Javahase** [comment]
What I forgot to mention on my side: To create this bug, you need to have at least one stack of the Item in the Mekanism Bin. Sorry for this misunderstanding.

**Comment by henkelmax** [comment]
Also tested that. Also works fine.

**Comment by Javahase** [comment]
And you really tried that with the Mekanism Bin having one stack (64 Items of a kind)?
I for one tried exactly your setup right now yet it didn't work as you can see here:
https://youtu.be/DO1iB1XFP2E

Just to be sure: You are using Pipez 1.2.1 as well right?

**Comment by henkelmax** [comment]
Oh, now I understand. It occurs only when the bin contains more than 64

**Comment by henkelmax** [comment]
Thanks for reporting this issue and sorry for the misunderstanding.
It should be fixed in the next version.

**Comment by Javahase** [comment]
It's alright. Thank you for the quick fix!

**Comment by henkelmax** [comment]
No problem!
