### ISSUE TITLE
Mekanism cardboard box can yeet pipe upgrades

### ISSUE THREAD

**Issue by jlp1528** [henkelmax/pipez#213]
**Bug description**
If an inventory is picked up with a cardboard box while an upgrade is present in an adjacent extracting pipe, the upgrade is deleted.

**Steps to reproduce the issue**
1. Set a pipe to extract from an inventory.
2. Apply pipe upgrade
3. Pick up inventory with cardboard box.
4. Upgrade does not pop and is not present when inventory is replaced.

**Expected behavior**
The upgrade should pop into the world like when an inventory is broken.

**Log files**
N/A

Versions

    Minecraft version: 1.20.1
    Mod loader: NeoForge
    Mod loader version: 47.1.76
    Mod version: 1.2.5

Other mods
Direwolf20 1.20 pack on FTB, version 1.10 as of post

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Does the pipe still visually look like its extracting after taking the block away?

**Comment by jlp1528** [comment]
No, it switches to the disconnected state.

**Comment by henkelmax** [comment]
and it doesn't throw out the upgrade?
Can you double check this. Sometimes it gets yeeted a little further away.

**Comment by jlp1528** [comment]
Unless it got thrown out of the range of my magnet, which is pretty decent, no, it just disappears.
