### ISSUE TITLE
universal (and item) pipez sucking cards out of LaserIO nodes

### ISSUE THREAD

**Issue by jlp1528** [henkelmax/pipez#214]
**Bug description**
As the title says, universal/item pipez treat LaserIO nodes like inventories and suck out their cards.

**Steps to reproduce the issue**
1. Place a LaserIO node and add a card.
2. Place a universal pipe on the side of the node you've added a card to.
3. Place an inventory so the card has somewhere to go.
4. Set pipe to extract.
5. Card extracted.

**Expected behavior**
LaserIO nodes should not be treated like inventories in this regard.

**Log files**
N/A

Versions

    Minecraft version: 1.20.1
    Mod loader: NeoForge
    Mod loader version: 47.1.76
    Mod version: 1.2.5

Other mods
Direwolf20 1.20 pack on FTB, version 1.10 as of post

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Thats probably intended by the mod author to be able to take out items. You need to disable the item pipe part in the universal pipe.
