### ISSUE TITLE
[BUG] 1.20.1-1.1.3 java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by SirKratosAurion** [henkelmax/pipez#215]
**Bug description**
java.lang.AbstractMethodError: Method de/maxhenkel/pipez/integration/waila/HUDHandlerPipes.appendServerData(Lnet/minecraft/nbt/CompoundTag;Lsnownee/jade/api/Accessor;)V is abstract

Also submitted to FTB https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4553

**Steps to reproduce the issue**
1. place down single vanilla chest
2. add 3 pipes to the top and another single chest on top
3. wrench the pipe connected to the lower chest

**Expected behavior**
The server should continue functioning and i should be able to use pipez

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
[crash-2024-01-12_02.38.52-server.txt](https://github.com/henkelmax/pipez/files/13911105/crash-2024-01-12_02.38.52-server.txt)

**Versions**
- MC: 1.20.1
- Mod Loader: Forge 47.1.3
- Pipez Mod version: 1.20.1-1.1.3

**Other mods**
See FTB Unstable 1.20.1

**Screenshots (Optional)**
None Avaiable

**Comment by henkelmax** [comment]
The version of Jade you are using is not listed on CurseForge or Modrinth. Please update the mod and check if that happens again.

**Comment by henkelmax** [comment]
Closed due to inactivity.
