### ISSUE TITLE
Crash while configuring Universal Cables

### ISSUE THREAD

**Issue by MuteTiefling** [henkelmax/pipez#216]
### Bug description

Game crashed after setting a universal cable connection to off. 

### Minecraft version

1.20.4

### Mod version

1.20.4-1.2.7

### Mod loader and version

Neoforge - 20.4.157

### Steps to reproduce

1. Place a universal cable next to something it can connect to
2. Sneak right click the connection twice to disconnect it
3. 

### Expected behavior

Not to crash :D

### Log files

https://gist.github.com/MuteTiefling/64bfcd73d336f910961a0d878ecc5f37

**Comment by henkelmax** [comment]
I tested it and it works perfectly fine. Does this happen without any other mods installed?

**Comment by MuteTiefling** [comment]
Haven't tested without other mods. It seem related to FE connections anyway, so testing without other mods would be impossible. 

Tested on a barrel without issues. The initial crash happened while connected to an Ad Astra machine. 

This time it happened while connected to an advanced wireless block charger. 

https://gist.github.com/MuteTiefling/e3868bd5920b00f739175c1a3dd04dd1

Worth noting that as soon as I load the world and look at the Universal Cable again, I crash immediately. This happened in the initial report too and I couldn't reliably get back into the world until I removed your mod. 

Here's the crash from looking at the faulty pipe: https://gist.github.com/MuteTiefling/f8c23a303cdfb7cc8df75ae2733e1f8f

**Comment by henkelmax** [comment]
![image](https://github.com/henkelmax/pipez/assets/13237524/5698f263-d1a4-45ae-b45d-82fc7711f5a8)
Works perfectly fine with Ad Astra

**Comment by henkelmax** [comment]
Nope nothing.

**Comment by henkelmax** [comment]
Closed due to inactivity. Feel free to reopen if you have more information.
