### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by dainte18** [henkelmax/pipez#220]
### Bug description

I have an atm9 server and i just put ultimate upgrades in my item pipez, and now my server cr4ashes everytime i try to load in. it didnt crash right away the first time but my crash report says its from the pipez mod causing the issue. server is crashing due to ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)

### Minecraft version

1.20.1

### Mod version

0.2.54

### Mod loader and version

forge48.1.0

### Steps to reproduce

try to join server, crash

### Expected behavior

not to crash

### Log files

	Issue tracker URL: https://github.com/henkelmax/pipez/issues 		at TRANSFORMER/pipez@1.20.1-1.2.6/de.maxhenkel.pipez.corelib.item.ItemUtils.isStackable(ItemUtils.java:301)

**Comment by dainte18** [comment]
update my forge is 47.2.20
this is the link to my crash log

https://panel.simplegamehosting.com/server/a8518d13/files/edit#/crash-reports/crash-2024-05-16_00.48.00-server.txt

**Comment by dainte18** [comment]
[crash-2024-05-16_00.48.00-server.txt](https://github.com/henkelmax/pipez/files/15328373/crash-2024-05-16_00.48.00-server.txt)

**Comment by dainte18** [comment]
sorry im very new to this 
Pipez (pipez), Version: 1.20.1-1.2.6
Observable (observable), Version: 4.4.1

**Comment by henkelmax** [comment]
Please check if this happens without any other mods.

**Comment by dainte18** [comment]
> Please check if this happens without any other mods.

its not really gonna be that simple, i had a system of 100+ botany hoper pots with insanium farmlard making all sorts off essences that went down into a ton of nethrite chest that i was then having go to drawers for each indiviual essence, and hooking all of that up to my me system using a sub net and a ton of auto crafters to automate greg tech, everything before the me system was using item pipes from pipez, i ad made about 7 ultimate upgrades, 40 of the next teir down, and about 20 more of the nest teir down after that and upgraded as many pipes as i could. so theres a lot to replicate plus this is my first time playing modded minecraft and i dont really know how to only install one mod. Id really appreciate your help. FYI i do have a back up off my sever about 20 hours before it happened so its not the end off the world to go back and do some testing if need be, but this was kinda be like my end game set up and idk how to do it without these pipes and the upgrades, they move so slow without them.

**Comment by henkelmax** [comment]
You don't need to use this specific world to check it. 
If you are using the CurseForge launcher, just create a new instance with just the mod. For other launchers that allows you to add mods from withing the launcher like prism the process is pretty similar. If you are struggling, please contact the launcher/mod loader support.

**Comment by henkelmax** [comment]
Closed due to inactivity
