### ISSUE TITLE
Pipez error when changing the output/input type

### ISSUE THREAD

**Issue by Prontary** [henkelmax/pipez#221]
### Bug description

When using the key to change the pipe between entry and exit of items, the same bug occurs and the game closes.

### Minecraft version

1.20.6

### Mod version

1.20.6-1.2.8

### Mod loader and version

Neoforge

### Steps to reproduce

Just make the connection between two chests and try to change one of the ends of the pipe as the item outlet.

### Expected behavior

It is expected to change the pipe connection for item input, thus transferring the items to the other chest

### Log files

https://drive.google.com/file/d/1D6MJSf0tFG72U9Lw2RHXN1If43QyElbx/view?usp=drive_link

**Comment by Prontary** [comment]
@henkelmax Thanks for the prompt attention, right after updating the pipez resulted in this exit (see image)! If the image is not displayed the message says that the pipez requires version 20.6.93 of the neoforge. I didn't find the same to download

![Screenshot_6](https://github.com/henkelmax/pipez/assets/59722150/d69b4664-8639-4315-bd2c-1ebdaf610ee7)

**Comment by henkelmax** [comment]
Just update NeoForge. Whats the issue?

**Comment by Prontary** [comment]
Thanks! Congratulations on your work

**Comment by Prontary** [comment]
Thanks! Worked perfectly
