### ISSUE TITLE
1.20.4 Neoforge Energy pipes needs update to start extracting.

### ISSUE THREAD

**Issue by KodYazanDruid** [henkelmax/pipez#223]
### Bug description

I am using pipez in my dev enironment and wanted to test my wrapped energy capability. It is working with mekanism cables fine but pipez pipes needs an update to start extracting 
https://github.com/KodYazanDruid/Eternal-Artifacts-Neoforge/blob/e53906e7dc75b41938005d238abcdda353bdfcac/src/main/java/com/sonamorningstar/eternalartifacts/network/SidedTransferAutoSaveToServer.java#L49 when i press the button that sends this packet pipe starts extracting.

### Minecraft version

1.20.4

### Mod version

Pipez 1.20.4-1.2.7

### Mod loader and version

NeoForge 20.4.235

### Steps to reproduce

Try to extract fe from any block that doesn't update neighbors regularly.

### Log files

there is no crash

**Comment by henkelmax** [comment]
Can you give exact steps to reproduce this issue?

**Comment by KodYazanDruid** [comment]
I simply put my block down and gave it some fe then i tried to transfer that fe to another battery block but it didn't work. Then i pressed the button that enables auto input/outputs it started transfering energy. Ik pipe doesn't have capability but the button i press sends a packet to server that updates the block and its neightbors. And i tought pipe needs some sort of update to start transfering.

**Comment by henkelmax** [comment]
Does this also happen with other mods that have blocks that store FE?

**Comment by KodYazanDruid** [comment]
It works fine on mekanism machines and it even works on my other generator block but for some reason it doesn't work with BatteryBlock. Even if i register its capability without wrapped class.

**Comment by KodYazanDruid** [comment]
I commented `distributePower()` method on the generator block and pipe is not extracting from the generator block. I am registering
https://github.com/KodYazanDruid/Eternal-Artifacts-Neoforge/blob/main/src/main/java/com/sonamorningstar/eternalartifacts/capabilities/ModEnergyStorage.java which extends EnergyStorage class as capability. I am not sure what is the issue.

**Comment by henkelmax** [comment]
> It works fine on mekanism machines and it even works on my other generator block but for some reason it doesn't work with BatteryBlock. Even if i register its capability without wrapped class.

I guess its an issue with your mod then. Double check your capabilities. NeoForge did a lot of changes to the capability system.

**Comment by KodYazanDruid** [comment]
![image](https://github.com/henkelmax/pipez/assets/45048634/eff16a95-cd9b-4d08-b650-688d1c9e7ee5)
The One Probe says ".get3DDataValue()" cannot invoke because side is null

Error is this  :https://gist.github.com/KodYazanDruid/24cb0e8c1698a699fca9348fea322879 pipe cannot find energy storage i think

**Comment by KodYazanDruid** [comment]
https://gist.github.com/KodYazanDruid/d45a97f22e8311ff7e11d107620cc173 prints this when i set extract mode on mekanism energy cube

**Comment by henkelmax** [comment]
This has already been fixed with b631f682e816e3b6ccb4d8fcbf4b3e9e2bd3913c

**Comment by henkelmax** [comment]
And its backported with 01deb9680953a2541c2398c72dc2cd2ff88d076f
