### ISSUE TITLE
Pipes don't drop when broken in 1.21

### ISSUE THREAD

**Issue by trunksbomb** [henkelmax/pipez#226]
### Bug description

Pipes don't drop when broken with pickaxe, and there doesn't appear to be any behavior for dropping it with a shift right click with wrench as is common with other pipe mods.

### Minecraft version

1.21

### Mod version

1.21-1.2.13

### Mod loader and version

NeoForge 21.0.30-beta

### Steps to reproduce

1. Place a pipe
2. Try to break it - doesn't drop items with wrench or pickaxe

### Expected behavior

Pipe should drop

### Log files

https://mclo.gs/YckkwuK

### Screenshots

https://github.com/henkelmax/pipez/assets/1904331/3261641c-4c04-4e69-83ef-aa43a903ddbd

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
