### ISSUE TITLE
No Pipez CurseForge Installation Available for 1.21.

### ISSUE THREAD

**Issue by tanayshah11** [henkelmax/pipez#227]
### Bug description

When I go the files tab on the CurseForge [Pipez](https://www.curseforge.com/minecraft/mc-mods/pipez/files/all?page=1&pageSize=20) page, I can't see any option for 1.21

### Minecraft version

1.21

### Mod version

1.21

### Mod loader and version

Forge 51.0.17

### Steps to reproduce

1. Go to [Link](https://www.curseforge.com/minecraft/mc-mods/pipez/files/all?page=1&pageSize=20)
2. Click on Filter By "All Game Versions"
3. There I cannot find any installations for 1.21 despite the modpack saying available for 1.21

### Log files

https://www.curseforge.com/minecraft/mc-mods/pipez/files/all?page=1&pageSize=20

**Comment by henkelmax** [comment]
Just visited your link and I'm seeing it:
![image](https://github.com/henkelmax/pipez/assets/13237524/c4be1e3b-52c9-4f7a-aaca-72d8fbf4c793)


https://www.curseforge.com/minecraft/mc-mods/pipez/files/5465392
