### ISSUE TITLE
Crash with Apotheosis in ATM9 No Frills

### ISSUE THREAD

**Issue by KianKhadempour** [henkelmax/pipez#228]
### Bug description

When filtering for 'apotheosis:core/*' on an item pipe, the game crashes.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.2.6

### Mod loader and version

Forge 47.2.21

### Steps to reproduce

1. Place down two chests with an item pipe in the middle.
2. Use a pipe wrench to set one side to extract.
3. Insert an ultimate pipe upgrade.
4. Add a filter with any Apotheosis gem as the item and at the end of the NBT data change 'apotheosis:core/(gem_type)' to 'apotheosis:core/*'.
5. Crash.

### Expected behavior

I am not sure if it is supposed to work like I wanted, but the reason I typed this in was to filter for all types of apotheosis gems.

### Log files

https://mclo.gs/PjqU04C#L6307

### Screenshots

https://github.com/henkelmax/pipez/assets/43736613/8dc3fd05-9aa3-46c6-9df8-9e00ca9a74eb

**Comment by henkelmax** [comment]
Just FYI setting `*` won't work. It shouldn't crash, but its invalid syntax.

**Comment by henkelmax** [comment]
Does this happen without any other item in the pipe filter?
Can you try what happens if you use `/give apotheosis:gem {NBT-DATA-HERE}` to give you the item with the exact NBT data you entered here.

**Comment by KianKhadempour** [comment]
> Does this happen without any other item in the pipe filter? Can you try what happens if you use `/give apotheosis:gem {NBT-DATA-HERE}` to give you the item with the exact NBT data you entered here.

This also crashes my world. Seems like its a problem with Apotheosis, then.

**Comment by henkelmax** [comment]
Yes.
