### ISSUE TITLE
Destination Filter / AE2 Inscriber

### ISSUE THREAD

**Issue by NassiC** [henkelmax/pipez#23]
**Bug description**
The destination filter is not filterring item types if the destination is an inscriber from Applied Energistics. If i add a white list filter for redstone, it works, and only redstone is pulled from the chest. If i then add a destination the the redstone filter, all items are pulled from the chest, and sent to the destination whitelisted for redstone only.

**Steps to reproduce the issue**
1. Setup 3 inscibers and one chest.
2. Filter Redstone with destination to the first insciber.
3. Put in any item (not redstone) and it will end up in the first inscriber filtered with redstone.
4. Same happens for all filters with a destination into an inscriber.

**Expected behavior**
When i set a destination with a specific item (here redstone) i expect only redstone to enter.
I get that redstone can enter another chest with no filter, but other items should not be able to enter this chest with an item and destination filter set. 

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.2
- Pipez version: 1.1.5
- AE2 version: 8.3.0-alpha.1

**Other mods**
I am useing All The Mods 6
https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files/2997714

**Screenshots (Optional)**
Screenshots of the issue.
![billede](https://user-images.githubusercontent.com/8850655/113902983-c63fe500-97d0-11eb-8efb-3928110647a3.png)
![billede](https://user-images.githubusercontent.com/8850655/113904236-25eac000-97d2-11eb-93db-ef5fe3e27888.png)

**Comment by henkelmax** [comment]
Is this bug reproducible with just chests?

**Comment by henkelmax** [comment]
Are you clicking on the right faces of the inscriber with the destination tool?

**Comment by NassiC** [comment]
Yes, i am clicking on the side the redstone is supposed to go in (in this case the south side).
It is also in that spot the other items are ending up. So that all seems right. Well except that it should only allow redstone in.

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/113981777-55d4aa80-9848-11eb-9dbb-2a626e619d49.png)

I tested it and it works perfectly fine.

**Comment by NassiC** [comment]
Okay i tried this setup, and when the pipe goes in the site the you pick with the destination tool, it works. But if the pipe goes in the back, and you pick a side with the destination tool, it is not working.

When picking another side then the pipe, it is not working with only chests either.

![billede](https://user-images.githubusercontent.com/8850655/113990843-2b87ea80-9852-11eb-8e12-a6a625682431.png)

With the insciber you need to be able to pick other sides then the one the pipe is touching, to place all items in. Like a furnace, where fuel goes in the side and items to smelt in the top.

**Comment by henkelmax** [comment]
I think you don't know hot this tool works.
It only works for a side where a pipe is connected.

**Comment by NassiC** [comment]
The items are getting in when picking a side the pipe is not connected to. So that part is working. And if you are not supposed to pick other sides then the one the pipe is connected to, then why specify the picked side?

**Comment by henkelmax** [comment]
How else would you do it?

**Comment by NassiC** [comment]
If the pipe is connected to the back of the inscriber, then i would pick the side (left or right) where the items has to go in, or the top. That way you dont have too connect pipes to all sides of the inscriber. Wich is what made it really awesome. :)

**Comment by henkelmax** [comment]
That's not the point. This mod does not 'teleport' items. This is just to specify a destination for a specific filter. Nothing more.

**Comment by NassiC** [comment]
Well it does work, and if it is not supposed to work, there is no reason to tell wich side is picked.
Then you really should remove that info, to not make it seem like it should work. And maybe fix the bug that it acctually works (except the filter part)

**Comment by henkelmax** [comment]
No, you still don't understand it.
