### ISSUE TITLE
Adding a Destination to a filter entry with just a NBT Data filter bypasses the NBT Data and transfers all items

### ISSUE THREAD

**Issue by laundmo** [henkelmax/pipez#230]
### Bug description

When filtering only using NBT, adding a Destination seems to bypass all filtering and just transfer all items

### Minecraft version

1.20.1

### Mod version

1.20.1-1.2.15

### Mod loader and version

Forge 47.2.20

### Steps to reproduce

1. Connect 2 chests with item pipez
2. put a diamon upgrade in the source chest
3. put multiple items, some with NBT data, in the source chest
4. create a NBT filter which should only transfer 1 of the items, only specifying the NBT to filter on (no item id or tags)
5. observer the 1 item being tranferred to output chest
6. add a Destination for the output chest to the filter
7. observe all items being transferred, ignoring NBT

### Expected behavior

I expected the Destination to apply only after the items have been filtered. I expetetec my NBT Data filter to still apply regardless of a Destination being set or not.

### Log files

https://mclo.gs/3RodC8t

### Screenshots

![image](https://github.com/user-attachments/assets/e7f7f9d4-2396-41a5-9fc3-a5b96af46d6e)

**Comment by henkelmax** [comment]
When setting a destination, the filter only applies for that exact destination. It doesn't limit it to that destination.

**Comment by laundmo** [comment]
> When setting a destination, the filter only applies for that exact destination. It doesn't limit it to that destination.

Yes, but i have exactly one possible destination, which is also set in the destination filter, and still no filtering is applied

**Comment by henkelmax** [comment]
Did you add an item to the filter?

**Comment by laundmo** [comment]
> Did you add an item to the filter?

No, only NBT as the screenshot is showing. Just NBT works if there isn't any destination, and is quite useful as i'm trying to filter Apotheosis armour and weapons which is hundreds of individual items or 2 forge tags (armours and tools)

**Comment by henkelmax** [comment]
You need to at least set a tag or an item in order for the filter to work.
