### ISSUE TITLE
1.21.1 Pipez compat issue

### ISSUE THREAD

**Issue by Zelioth** [henkelmax/pipez#236]
### Bug description

Pipez Mekanism support needs to be updated to the new chemical API to not break things 

EMI currently fails due to an error. I reported the error to Mekanism and they pointed me towards Pipez. 

### Minecraft version

1.21.1

### Mod version

1.2.17

### Mod loader and version

21.1.31

### Steps to reproduce

yes

### Expected behavior

yes

### Log files

https://gist.github.com/Zelioth/caf2aa89b9ba733e1832661a9c6acfd1

**Comment by henkelmax** [comment]
Has already been fixed in #235
