### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by SirTwsted** [henkelmax/pipez#238]
### Bug description

I was searching my inventory within+ a chest, next thing I know I crashed.

https://pastebin.com/uzHKJJtF

### Minecraft version

1.21.1

### Mod version

1.2.17

### Mod loader and version

NeoForge v21.1.61

### Steps to reproduce

I was searching my inventory within+ a chest, next thing I know I crashed.

### Log files

https://pastebin.com/uzHKJJtF

**Comment by henkelmax** [comment]
> I was searching my inventory within+ a chest, next thing I know I crashed.

Is this a mod? If yes can you link it to me?

**Comment by SirTwsted** [comment]
If you are asking about the chest I used, if it was a modded chest, then yes.  I was searching within a Sophisticated Storage chest,
where I have all my items currently stored.  When I was searching for something, 5 seconds in opening the chests the crash happened.
Anything further than that, I have no clue.

https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage

**Comment by henkelmax** [comment]
Does this happen consistently? If yes please provide the exact steps to reproduce the issue in a clean environment.

**Comment by N-Wither** [comment]
`IGasProvider` is replaced by `IChemicalProvider` in Mekanism 1.21.x

**Comment by henkelmax** [comment]
Oh yeah you are using an outdated mod version.

**Comment by F0x06** [comment]
HI @henkelmax  ! I just got the `java.lang.NoClassDefFoundError: mekanism/api/providers/IGasProvider` in my `1.21.1-NeoForge` modpack, any plans to fix this ? All my mods are up to date,

* Mekanism-1.21.1-10.7.8.70
* pipez-neoforge-1.21.1-1.2.17
* neoforge-21.1.95

Thanks.

**Comment by F0x06** [comment]
Just found out that Modrinth has a newer version `1.2.19`, do you plan updating CurseForge or i need to plan switching to Modrinth ?
