### ISSUE TITLE
Duplication with item pipes

### ISSUE THREAD

**Issue by Chubrel** [henkelmax/pipez#239]
### Bug description

Duplication bug with item pipes and Ex Nihilo Auto Compressors

### Minecraft version

1.18.2

### Mod version

1.1.5

### Mod loader and version

Forge 40.2.21

### Steps to reproduce

Using mod Ex Nihilo: Sequentia 20230528-221633.
Place Auto Compressor and put items in it (diamonds, for example)
Place item pipe next to it and place chest next to pipe.
Use pipe wrench on the end to compressor, so it start to transfer items to chest.
You would see, that items just appers in the chest.

### Expected behavior

No duplication occure; items from right part of the compressor menu are translated to chest.

### Log files

This doesn't create any log messages

### Screenshots

![Screenshot of the setup](https://github.com/user-attachments/assets/2eb8c5f9-8dc7-43f7-a41c-1c400ee3a58d)

**Comment by henkelmax** [comment]
This minecraft version is no longer supported.

**Comment by Chubrel** [comment]
Bug occurs in 1.20.1, but it does so with other pipes too, so I think it is Ex's issue.
