### ISSUE TITLE
Shift click to create filters

### ISSUE THREAD

**Issue by NassiC** [henkelmax/pipez#24]
**Is your feature request related to a problem? Please describe.**
When needing to add many items to a filter, an example could be in a mining setup where all ores has to go to one place, and all diamonds, redstone, coal etc. has to go to another. In this case adding all these items is quite a task in a big modpack. 

**Describe the solution you'd like**
When in the "Filter screen (See pic)" shift clicking an item would make a filter for it.

**Describe alternatives you've considered**
Clicking add first, and then allowing a shiftclick to fill the item in would be a greate step to speeding up the task, but allowing me to not click "Add and Submit" everytime like i suggest above would be even better. :)

**Additional context**
Just shift click an item here, to add a filter with that item and standard settings. If you then have 10 or like here 16 items in your inventory you can just shift click them vary fast, and you are done. :)
![billede](https://user-images.githubusercontent.com/8850655/113905980-08b6f100-97d4-11eb-898c-dad2572c496e.png)

**Comment by henkelmax** [comment]
It should be working in the latest version.
