### ISSUE TITLE
Massive Lag Generated by Pipez - 70% CPU Thread Usage

### ISSUE THREAD

**Issue by TheGameAce** [henkelmax/pipez#242]
### Bug description

Tried Pipez to replace Mekanism's laggy logistical transporters. Spiked from 40% of CPU thread to 70% with the switch. The system of transporters (& then pipez) I've been using is for a Productive Bees farm with a fair number of hives.

Addendum: Did some further testing. TPS still drops significantly with only a fraction of the hives connected.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.2.5

### Mod loader and version

Forge 47.3.5

### Steps to reproduce

N/A

### Expected behavior

N/A

### Log files

https://spark.lucko.me/xL7RQk2nSp

**Comment by henkelmax** [comment]
If you take a look the lag is actually caused be the logic if an item can be inserted into their inventory of the productive bees mod. Theres not much we can do about other mods inventory logic being slower.

**Comment by TheGameAce** [comment]
Ah gotcha, my bad. Appreciate the insight at least.
