### ISSUE TITLE
Infinity Pipe Upgrade slowing server down to 180 seconds per tick when inputting into an AE2 Matter Condenser

### ISSUE THREAD

**Issue by IAmB34N** [henkelmax/pipez#245]
### Bug description

Hooking a fluid pipe to a sink, then adding in an infinity upgrade, then leading that into a matter condenser from AE2, will crash a server. (happened in Project Architect 2 with an 8GB server)

### Minecraft version

1.20.1

### Mod version

pipez-1.20.1-1.2.5.jar

### Mod loader and version

Forge 47.3.7

### Steps to reproduce

1. Place down a sink
2. Place a fluid pipe coming out of it
3. Hook this pipe to a Matter Condenser from AE2
4. Have an output for the Singularities
5. Have your server so laggy, that it crashes every minute!

### Expected behavior

items to input normally without lag

### Log files

https://gist.github.com/IAmB34N/b0e5b7a0e459a7c9946da0cc3de9836f

### Screenshots

none to be seen, it crashed instantly

**Comment by henkelmax** [comment]
Don't use infinite upgrades. They are prone to such issues. There's a reason why they can't be crafted.
