### ISSUE TITLE
Watchdog crash Pipez and fluxnet crash

### ISSUE THREAD

**Issue by YOYOK9** [henkelmax/pipez#25]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Watchdog crashed, seems to be an issue between Fluxnet and pipes directly connect to each other. 

**Steps to reproduce the issue**
1. Place flux net in or out on energy pipe,
2. add ultimate filter
3. wait?
4. 

**Expected behavior**
No server crash
**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).
https://gist.github.com/YOYOK9/6819c164bb9862322e7c9842bb756e87

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.4
- Mod version: 1.16.5-1.2.2

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
https://gist.github.com/YOYOK9/4528b4788eabaa664ed0f59a97c7b838

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
I tested it and it worked fine. Can you please test it with just the fluxnet mod and the pipez mod installed and do a minimal setup?

**Comment by Javahase** [comment]
Hello,

I had the same problem with Watchdog as well. As I narrowed down the possibilities which could be helpful to fix this problem, I found this helpful little mod called "Spark". With that, I waited for the next lag spike. When it appeared, the Profiler of Spark told me this:
![image](https://user-images.githubusercontent.com/42071641/114309579-e8df4000-9ae7-11eb-9f62-61f4ccae465f.png)

Then, I began replacing every energy pipe by Pipez with Mekanism cables. After that, the lag spikes stopped.

I'm running the latest version of Pipez (1.16.5-1.2.4)

**Comment by henkelmax** [comment]
Should be fixed in 1.2.6. Can you test it with this version again?

**Comment by Javahase** [comment]
Hello,

so far I haven't encountered any more issues. I think it is fixed. Thanks a lot for the fast fix!

I'll notify you asap if I encounter this issue again.

**Comment by henkelmax** [comment]
>Hello,
>
>so far I haven't encountered any more issues. I think it is fixed. Thanks a lot for the fast fix!

No problem!

> I'll notify you asap if I encounter this issue again.

Thank you!
