### ISSUE TITLE
Pipe upgrade loading world

### ISSUE THREAD

**Issue by KrivalCell** [henkelmax/pipez#250]
### Bug description

Hi, I'm playing on a modpack with your mod, and I don't know why, but pipe upgrades are very heavily loaded on the internal server (ultimite pipe upgrade is most loaded)

### Minecraft version

1.21.1

### Mod version

1.21.1-1.2.19

### Mod loader and version

Neoforge 21.1.83

### Steps to reproduce

1. place a item pipe
2. Put an upgrade in the pipe
3. The pipe begins to load the game

### Expected behavior

Pipes will stop loading the game

### Log files

https://gist.github.com/KrivalCell/7b47f615ddecd0ca20bc442939812f7f

### Screenshots

![2024-12-07_23 07 21](https://github.com/user-attachments/assets/b4796d60-f0a9-4035-832a-6ffd3eb55d04)

**Comment by henkelmax** [comment]
Can you do a spark profile of this?

**Comment by KrivalCell** [comment]
> Can you do a spark profile of this?

What do you mean?

**Comment by henkelmax** [comment]
https://spark.lucko.me/

**Comment by KrivalCell** [comment]
https://spark.lucko.me/6UeNkcoVmQ

**Comment by KrivalCell** [comment]
> https://spark.lucko.me/6UeNkcoVmQ

Perhaps the problem appears specifically when connecting the pipe to tesseract, because if I make a buffer between the pipe and tesseract from a regular chest, there is no load on the world

**Comment by henkelmax** [comment]
The majority of the lag seems to be caused by caused by natures aura and crafting tweaks.
