### ISSUE TITLE
Energy pipes do not work in 1.21.4

### ISSUE THREAD

**Issue by AEAEAEAE4343** [henkelmax/pipez#252]
### Bug description

I was looking for a pipe mod that could test some of the features of my mod. However, after significant testing, I concluded that Energy Pipes are broken in 1.21.4 (possibly for all 1.2.19 builds). Adding a million breakpoints in my mod gave my this conclusion:
The pipe does fetch whether the block has any IEnergyStorage capability when placing the pipe or through a block update when placing the block itself. It then visually connects, but it makes no calls to the actual functions in the IEnergyStorage interface.

### Minecraft version

1.21.4

### Mod version

1.21.4-1.2.19

### Mod loader and version

NeoForge 21.4.26-beta

### Steps to reproduce

Place a creative energy cell (or anything that allows energy extraction). Place another block that can receive energy. Add a pipe and test it: no energy gets transferred.

### Expected behavior

Pipe should transfer energy.

### Log files

Log file showed 0 output from Pipez and is cluttered with REI crashes, so I omit it for now.

**Comment by henkelmax** [comment]
Please provide logs. Which mod are you using for energy?

**Comment by AEAEAEAE4343** [comment]
I'm extremely sorry for bothering you, this was my own fault.
