### ISSUE TITLE
Gas pipe recipe warnings if Mekanism is not installed

### ISSUE THREAD

**Issue by Tander** [henkelmax/pipez#27]
**Bug description**
I'm getting this warnings in console:

06:31:20.087
Parsing error loading recipe pipez:gas_pipe
com.google.gson.JsonSyntaxException: Unknown item 'mekanism:alloy_infused'

06:32:31.544
Couldn't parse loot table pipez:blocks/gas_pipe
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'pipez:gas_pipe'

It seems you need to add a condition in recipe if Mekanism is presented.

**Steps to reproduce the issue**
Start the game without mechanism installed

**Expected behavior**
No warnings

**Log files**

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.2
- Mod version 1.2.1

**Comment by henkelmax** [comment]
This is normal. Recipes are JSON files. You can't change them programmatically if a mod is not installed. As far as I know, every mod does it like that.
This error message does not affect the game in any way.

**Comment by Tander** [comment]
Well, you can. Here is example from quark:
https://github.com/Vazkii/Quark/blob/master/src/main/resources/data/quark/recipes/building/crafting/candles/candle_basic.json

**Comment by henkelmax** [comment]
Oh, I didn't know of that thank you very much!

**Comment by henkelmax** [comment]
It should be fixed in the next veriosn.
