### ISSUE TITLE
Pipez in combination with QuantumEntangloporter

### ISSUE THREAD

**Issue by Double13** [henkelmax/pipez#29]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Pipez in combination with QuantumEntangloporter = massive TPSs drop

**Steps to reproduce the issue**
Build this setup: https://ibb.co/1T8M2j3 (use in the log file below)
The red line indicates a cut between the QuantumEntangloporter  channels
*optional8 apply the used config https://pastebin.com/HXSrGtiN (Makes pipez the same as mekanism)

Thermal Machines MUST be used as they seem to be linked to the huge TPS drop. When using Mekanism I have yet been able to produce this issue as easy as shown here. 

**Expected behavior**
The issue seems to be as followed. When using pipez in combination with a mekanism QuantumEntangloporter and Thermal expansion it massively drops the TPS. Please note that just building a quick 1 Thermal machine does not do the trick Please see below the setup that was used together the the Spark mod output info

**Log files**
Note that ONLY the machine on the right top is smelting zinc/copper dust to make Create brass.
All other machines remain off !
Profiler ran for 30 seconds before switching to the next setup 

Idle mode: 20 TPS
https://spark.lucko.me/ktH6PXrSus
Setup 1: Server running at 20 TPS
https://spark.lucko.me/u0GRfvLAyv
Setup 2: Server running at 20 TPS
https://spark.lucko.me/SB7k6MMTCy
Setup 3: Server running at 20 TPS
https://spark.lucko.me/ib7U6YirpA
Setup 4: Server running at 10 TPS
https://spark.lucko.me/aAUWOHCVfT
Setup 5: Server running at 4 TPS
https://spark.lucko.me/cJwkkO0Y1b
Setup 6: Server running at 4 TPS
https://spark.lucko.me/7UGCGOeXn8
Setup 7: Server running at 4 TPS
https://spark.lucko.me/09G8Qe3S3e
Setup 8: Server running at 4 TPS
https://spark.lucko.me/dLIna1xOGR
Afterwards back in idle mode: https://spark.lucko.me/oRJhYue88x

**Versions**
ATM6 1.5.10

**Other mods**
ATM6 1.5.10

**Screenshots (Optional)**
Setup: https://ibb.co/1T8M2j3

**Comment by henkelmax** [comment]
This does not seem to be caused by the pipez mod. According to the profiles you created, mekanism is the problem.
Have you reported that issue to mekanism?

We had similar issues when creating some kind of loop between the entangloporter and the pipe. If you never extract and insert from the same energy network, the pipez mod shouldn't cause any lag.

**Comment by Double13** [comment]
Well as the test setup shows the only change is the pipez from your mod thus i forward the issue here, I am not a real pro in reading these logs I have a general idea whats going on but thats it (and want to leave it like that).

My only notice was that on the public server i play on the whole server grinded to a hold when i swapped out the mekanism pipes to Pipez. As such here i am :) But if you are convinced it might be mekanism i could post it on mekanism and see it unsolved for the next months but my honest oppinion remains it might be something with pipez as its the item that got changed before the lag erupted. 

Thanks for the great mod and the quick reply

**Comment by henkelmax** [comment]
The cause of lag in the profiles is 100% mekanism, so please report it also to their tracker.

**Comment by Double13** [comment]
Well thanks for the support I see git added a link here so ill set the ticket to close here and hope it ever gets fixed :)

**Comment by henkelmax** [comment]
Thank you!

**Comment by henkelmax** [comment]
It should be fixed in the next version.
