### ISSUE TITLE
Understanding universal pipes

### ISSUE THREAD

**Issue by MikaelS111** [henkelmax/pipez#30]
Hiya!

First off - great mod! I love it's simplicity, yet it is advanced when you dig into it.

I am playing around with Industrial Foregoing (FE from now on) and want to use the Universal pipes to get energy to machines (The machine can work without power, but is more efficient with) but also extract the content from them. 

This causes some strange behaviour, so I would love some insightful suggestions to where I'm doing wrong.

1. As generator for power, I am using the Stirling Generator from Thermal Series. Coal is the fuel. No biggie here. Pipe is set to extract here with no upgrade.
![Alt Text](https://i.imgur.com/wkTPWEj.jpg)

2. I then have a Fluid Extractor from FE that will extract latex from trees. It gets power from the Stirling straight in.
![Alt Text](https://i.imgur.com/EEWr3xd.jpg)

3. A block Placer from FE provides the tree. It gets power from the Stirling straight in.
![Alt Text](https://i.imgur.com/hnl4gy8.jpg)

4. As you can see, power in the Fluid Extractor is full.
![Alt Text](https://i.imgur.com/IRmpkRq.jpg)

5. I want to extract the latex into the Latex Processing Unit from FE.
![Alt Text](https://i.imgur.com/tvc5mIe.jpg)

6. In order to do that, I need to shift-right click with the wrench on the pipe on the Fluid Extractor in order to set it to extract.
![Alt Text](https://i.imgur.com/co5UTtd.jpg)

7. However, when I do this, The fluid is transferred fine but the power is drained to 0 in the Fluid Extractor. (this is it going down)
![Alt Text](https://i.imgur.com/W2fEsWT.jpg)

8. I've tried with an Ultimate Pipe Upgrade, but no matter what I set the "item pipe" or the "energy pipe" to, nothing makes the power come in.

So how do I proceed from here?

- Yes, I could just have the pipe go out from the other side, but that kind of makes the universal pipe obsolete (to me at least).

Kind Regards,
Mikael

**Comment by henkelmax** [comment]
If you extract from a side, you can't put stuff in. You need to connect it on another side.

**Comment by MikaelS111** [comment]
> If you extract from a side, you can't put stuff in. You need to connect it on another side.

Hm ok. Then I'm missing the point of universal pipes. Is that just for extracting then?

**Comment by henkelmax** [comment]
If you set a side to extract, it can only extract.
The difference to the other pipes is that it can handle every type (Items, energy, fluid, gasses)

**Comment by MikaelS111** [comment]
> If you set a side to extract, it can only extract.
> The difference to the other pipes is that it can handle every type (Items, energy, fluid, gasses)

Ok, it does makes sense. If you have a machine that outputs both fluid and items, then you can have 1 extraction point instead of 2.

Thanks for the clarification :)

**Comment by henkelmax** [comment]
No problem :)
