### ISSUE TITLE
[Feature Request] copy upgrade nbt data

### ISSUE THREAD

**Issue by delta2k** [henkelmax/pipez#32]
**Is your feature request related to a problem? Please describe.**
no way of copy nbt/filtering from upgrade.

**Describe the solution you'd like**
add the ability to copy upgrades nbt/filtering list to another upgrade and also ability to clear the upgrade of data. so upgrading from one upgrade to the next is easier

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by henkelmax** [comment]
This feature already exists.
Just craft a configured and a unconfigured upgrade together

**Comment by delta2k** [comment]
ok. but can you include descriptions in the upgrade to inform people its possible.  thanks

**Comment by henkelmax** [comment]
I think this is already in JEI

**Comment by delta2k** [comment]
jei-1.16.5-7.6.4.87
pipez-1.16.5-1.2.7
forge 36.1.13

with those installed jei doesn't show any info about the upgrades.

**Comment by henkelmax** [comment]
Alright, I might add that sometime

**Comment by delta2k** [comment]
that would be great thanks.
