### ISSUE TITLE
How does the whitelist feature work?

### ISSUE THREAD

**Issue by RGFTheCoder** [henkelmax/pipez#35]
When piping with a filter set to overworld matter (custom fluid added in seaopolis modpack) into 4 blast chillers, I was routinely getting tin piped out (before it alloyed since it was in a tinkers forge), and had to set it to blacklist with 4 inverted filters with specific destinations before it stopped moving tin.

Could you add an explanation to how to use whitelist/blacklist to the readme on Curse and here?

**Comment by RGFTheCoder** [comment]
Nevermind, tin still gets piped into the blast chillers

**Comment by RGFTheCoder** [comment]
Why was this closed? I still can't get whitelisting to work?

**Comment by henkelmax** [comment]
> Nevermind, tin still gets piped into the blast chillers

You said nevermind, so I thought you found it out.

**Comment by henkelmax** [comment]
If you want to set a whitelist for a specific location, this whitelist just applies to this specific location, stuff can still go into other destinations.
