### ISSUE TITLE
Are upgraded pipes less laggy than stock pipes?

### ISSUE THREAD

**Issue by mm04926412** [henkelmax/pipez#39]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/pipez/faq)!**

A lot of the lag on my server is from pipez with ultimate upgrades in them where ultimate upgrades have been used basically everywhere. Would the lag be reduced if these were replaced with lower tier upgrades?

**Comment by henkelmax** [comment]
Yes, higher upgrades produce more lag. This is especially the case for item pipes, since the lowest variant doesn't transfer every tick.

**Comment by mm04926412** [comment]
thanks, do any upgrades on the item pipe NOT transfer every tick but allow a stack to be transferred at a time? If not would you consider adding "eco mode" to the ultimate upgrade pipes so that they slowly pull out full stacks?

**Comment by henkelmax** [comment]
You can fully customize the rates in the config.
