### ISSUE TITLE
Ultimate / Combo Pipe to handle multiple functionalities

### ISSUE THREAD

**Issue by StanleyMcClister** [henkelmax/pipez#4]
It would be amazing to have a single pipe that can handle all 4 or combination of functionalities that you have already implemented. 

So something like an ultimate pipe that either can handle all the functionalities or the ability to create combo pipes with only a few of the functionality. For example if you want pipe to handle both energy and items you make a pipe for that or if you want one to a single pipe to handle energy, items, and fluids you could do that. If you wanted to go for the combo-pipe idea.

**Comment by henkelmax** [comment]
Thanks for suggesting this. It should be up on CurseForge very soon.

**Comment by StanleyMcClister** [comment]
Amazing Work! Thanks for the feature!

**Comment by henkelmax** [comment]
No problem!
