### ISSUE TITLE
 Filter Destination Tool should have priority over distribution mode

### ISSUE THREAD

**Issue by aaronhowser1** [henkelmax/pipez#40]
**Describe the solution you'd like**
Items that have a set destination should prioritize that destination

![image](https://user-images.githubusercontent.com/15698722/119233401-81f17580-baee-11eb-8c5a-6c83b1203dd8.png)
Click on this
![image](https://user-images.githubusercontent.com/15698722/119233412-8e75ce00-baee-11eb-9d74-6b5c9a9828d0.png)
Click on this
![image](https://user-images.githubusercontent.com/15698722/119233416-93d31880-baee-11eb-8192-a03c88ab9e28.png)
It's set in the list
![image](https://user-images.githubusercontent.com/15698722/119233423-9b92bd00-baee-11eb-9225-e2ee653dcd11.png)
All three items go to the other, closer destination

**Comment by henkelmax** [comment]
Destinations are completely independent to distribution modes.

**Comment by aaronhowser1** [comment]
Would the destination EVER be used then? If the dist mode is nearest first, and the destination isn't the nearest block, it'll go to the nearest block.

**Comment by henkelmax** [comment]
That's what blacklists and invertions are for

**Comment by jarquafelmu** [comment]
@henkelmax what is the way to do this with blacklists and invertions? I have a similar problem where I have a filtered destination set but the pipe is sending the item everywhere else

**Comment by henkelmax** [comment]
If you set a destination on a filter, you need to either blacklist it everywhere else, or switch to blacklist.
