### ISSUE TITLE
[Feature Request] Support for nested tags

### ISSUE THREAD

**Issue by MrBazlow** [henkelmax/pipez#42]
**Is your feature request related to a problem? Please describe.**
Pipez filters will accept tags as a filter criteria, they do not however acknowledge nested tags 
e.g. forge:gems and forge:gems/certus_quartz_crystal

**Describe the solution you'd like**
Add functionality similar to Mekanism Logistical Sorter which accepts wildcards to catch all nested options. Perhaps a gated functionality reserved for the ultimate pipe upgrade. 

**Describe alternatives you've considered**

- Creating individual filters for nested tags 
- Using other options such as the Mekanism Logistical Sorter to organise and sort
- Adding tags to items with KubeJS

**Additional context**
![image](https://user-images.githubusercontent.com/67396813/120397587-7b55d000-c330-11eb-8f66-2c676a7fc1f3.png)
![image](https://user-images.githubusercontent.com/67396813/120397452-434e8d00-c330-11eb-8ade-373c6675d7b1.png)

**Comment by henkelmax** [comment]
What's the problem?
`#forge:gems` is the equivalent to `#forge:gems*`.

**Comment by MrBazlow** [comment]
It appears not to be. 

I sandboxed this before posting by filling a chest with Emeralds, Diamonds as well as gems from mods such as Aquamarine from Astral Sorcery, Certus Quartz from Applied Energistics 2 and Fluorite from Mekanism. Using a pipe with an ultimate pipe upgrade , set to whitelist and with a filter for tag forge:gems only the vanilla Diamonds and Emeralds were moved. This appears to be because the vanilla gems have two tags, forge:gems and forge:gems/diamond or forge:gems/emerald while the modded gems using nested tags have not included a separate forge:gems tag.

Other mods such as Botania, Ars Nouveau and Thermal Series actually include two tags for each gem so this is more of a feature request to work around other mods missing tags although i'm sure it would be useful elsewhere too.

**Comment by henkelmax** [comment]
> This appears to be because the vanilla gems have two tags, forge:gems and forge:gems/diamond or forge:gems/emerald while the modded gems using nested tags have not included a separate forge:gems tag.

Then this is an oversight by these mods.
I don't plan on adding a wildcard modifier to tags.
This would drastically decrease performance, since ever tag would need to be matched against this.

**Comment by MrBazlow** [comment]
Fair enough, thank you for the reply.
