### ISSUE TITLE
Can pipes input to a face they are set to extract from?

### ISSUE THREAD

**Issue by shitwolfymakes** [henkelmax/pipez#43]
I have a compact setup of drawers and crafters, and I'm using universal pipes with Advanced upgrades to move power an items around. However, to do this, all pipes need to be extracting from the face they need to input to(bottom). I blacklist everything, and use the filter destination tool to properly route the items to their destinations (all filters are inverted to negate the blacklisting of the destination). 

When I set it up like that, nothing is moving around. However, when I do the same thing, but use one set of pipes to extract items from the top, and a separate set of pipes to input via the bottom, everything works as expected.

**Comment by henkelmax** [comment]
Pipes can not insert on sides they are extracting.

**Comment by Kangy1103** [comment]
I know this is a _really_ old issue, but are there any plans to make this possible? You could become the replacement for EnderIO conduits making everything possible from one side of a machine! :D
