### ISSUE TITLE
Fluids coming out of Tinkers Construct smeltery when they shouldn't.

### ISSUE THREAD

**Issue by susantussing** [henkelmax/pipez#44]
**Bug description**
When pipe attempts to pull a whitelisted (anti-blacklisted?) fluid from a smeltery where the bottom fluid is something else that can't normally pass the filter, it extracts that fluid anyway.

**Steps to reproduce the issue**
1. Tinker's Construct smeltery with fluid pipes leading to two casting basins.  Diamond upgrade on extraction point.
2. Set filter mode to blacklist and add an inverted filter for fluid A, with destination "any".  Distribution mode nearest-first.  On when powered by redstone with a lever above and turned on.
3. Melt one block to become fluid A.  It enters first casting basin.
4. Melt one block to become fluid B.  It remains in smeltery.
5. Add another block of fluid A.  Both fluid A and fluid B come out into casting basins and form blocks.  

**Expected behavior**
I believe this is a problem with interacting with Tinkers Construct; it's extracting some of fluid B just to get to the fluid A it's supposed to be able to extract.  Even weirder, on the Seaopolis modpack, Overworldian Matter is a non-standard block size, and it doesn't just pull one block of it out--it pulls exactly 100mb, and then proceeds to distribute it among multiple casting basins instead of just the first available.  I'm pretty sure this is because it isn't expecting to be getting it at all, so it isn't consistently imposing the distribution order.  This didn't happen with the metals I tried.

In either case, it only pulls the wrong fluid when the correct one is present but not yet at the bottom of the smeltery list.

**Log files**
Doesn't seem to be anything notable there for it.

**Versions**
- Minecraft 1.16.5
- Forge 36.1.16
- Pipez 1.2.7

**Other mods**
Tinkers Construct 3.0.3.152

**Comment by henkelmax** [comment]
Can you send a screenshot of your setup?

**Comment by HermoidIronfist** [comment]
> Can you send a screenshot of your setup?
I'm having the same problem!
![2021-06-06_13 33 10](https://user-images.githubusercontent.com/27518328/120936167-0a197280-c6cc-11eb-95ef-18af5407de7f.png)
![2021-06-06_13 33 21](https://user-images.githubusercontent.com/27518328/120936170-0c7bcc80-c6cc-11eb-843f-e677f451c77f.png)
![2021-06-06_13 33 39](https://user-images.githubusercontent.com/27518328/120936172-0e459000-c6cc-11eb-8723-299bc44fc15d.png)

**Comment by henkelmax** [comment]
> ![2021-06-06_13 33 21](https://user-images.githubusercontent.com/27518328/120936170-0c7bcc80-c6cc-11eb-843f-e677f451c77f.png)

Your setup only blacklists clay and tin. Other fluids still get extracted. So if you smelt any other block it gets into the nearest fluid containers.
It seems that one casting basin is set to extract. This causes the other basin to get filled.

I can't understand your problem in these screenshots.

**Comment by susantussing** [comment]
I can get some screenshots later today hopefully.  I can guarantee you that none of the other basins in my case were set to extract, and the filter is exactly as I described.  If you follow the instructions to replicate, you should get the same result.  Is it failing to occur when you follow those instructions exactly, @henkelmax?

**Comment by henkelmax** [comment]
I just tested it and it works perfectly fine.
![image](https://user-images.githubusercontent.com/13237524/120937139-09083580-c70c-11eb-82e2-a87232ad928f.png)

**Comment by susantussing** [comment]
I'm not sure you followed all the steps exactly, since the lever is missing, there's no indication that you actually put two different kinds in at once, and you used a different kind of pipe than I specified.  I've since checked (after these screenshots) and the problem still does occur with the ultimate pipes, but I don't think you followed the replication steps exactly.  I have screenshotted along the entire process.

Initial setup:
![2021-06-06_14 06 34](https://user-images.githubusercontent.com/8576412/120937255-2ae4c680-c6d2-11eb-9fd0-df3757b7ae9f.png)
Filter:
![2021-06-06_14 07 58](https://user-images.githubusercontent.com/8576412/120937269-4354e100-c6d2-11eb-9844-4b71a0c2b856.png)
Single block of gold is cast fine:
![2021-06-06_14 08 51](https://user-images.githubusercontent.com/8576412/120937281-5071d000-c6d2-11eb-905c-e8048c227c4e.png)
Iron remains in smeltery without going into any casting basin when it's alone:
![2021-06-06_14 09 43](https://user-images.githubusercontent.com/8576412/120937292-6089af80-c6d2-11eb-9c7c-4707d8ba8632.png)
Both iron and gold are extracted and cast when another block of gold is introduced, the iron apparently first:
![2021-06-06_14 10 29](https://user-images.githubusercontent.com/8576412/120937309-7bf4ba80-c6d2-11eb-92cb-dd38b85e057b.png)

So this is without any Seaopolis-specific stuff, that's still clearly not working as it should.  With the introduction of Seaopolis' molten overworldian matter allowed in place of the molten gold, with a third casting basin thrown in just to be sure it wasn't just something happening with two.
Here's how much was in the smeltery to start with.  (Odd amount because I missed screenshotting the first time.)  ![2021-06-06_14 16 46](https://user-images.githubusercontent.com/8576412/120937363-aa729580-c6d2-11eb-8633-339795ead114.png)
Here's how much gold is left after the one block of overworldian matter is added:
![2021-06-06_14 17 22](https://user-images.githubusercontent.com/8576412/120937403-d8f07080-c6d2-11eb-8db6-c06a61856272.png)
That green block is still in the smeltery because the gold split itself between all available basins instead of all going into one. ![2021-06-06_14 17 28](https://user-images.githubusercontent.com/8576412/120937408-ddb52480-c6d2-11eb-9835-4c239a2d67a8.png)

But that latter behavior is probably not super relevant if it weren't extracting anything but the permitted fluid at all and probably has to do with something weird about that custom block/fluid.  It's just that's why Seaopolis players are noticing this.

**Comment by henkelmax** [comment]
Did exactly your setup. Works perfectly fine.

![image](https://user-images.githubusercontent.com/13237524/120937932-afeed080-c710-11eb-80c3-eb60b4a18af4.png)

Please make sure it happens without any other mods installed.

**Comment by henkelmax** [comment]
Closed due to inactivity.
