### ISSUE TITLE
Trying to understand filtering and destination control

### ISSUE THREAD

**Issue by jarquafelmu** [henkelmax/pipez#46]
I've been trying to figure out how to make it so certain items can only go to specific destinations. Initially I presumed that if I set an item to be filtered with a destination then it would only go to that destination, but this hasn't been working.

One way I've been able to do it was to create a rule for every place it can go and an inverted rule for every place it can't go. Is that the intended way? 
![image](https://user-images.githubusercontent.com/5807272/121252349-1edd3e00-c865-11eb-8a80-69468498d5d7.png)
![image](https://user-images.githubusercontent.com/5807272/121252422-34eafe80-c865-11eb-8170-7a458ec227f0.png)

It works but it seems really cumbersome and not very practical if you have a lot of items going to one of a few destinations.

In my use case I have a number of destinations and items coming from sources going to specific destinations. 
![image](https://user-images.githubusercontent.com/5807272/121252837-b6db2780-c865-11eb-8ca5-7d6171dcf7b4.png)

Is there a better way of doing this?

As it stands for every single item I would need to make 8 rules in order to control where it goes and ensure that it only goes to one location.

**Comment by jarquafelmu** [comment]
Because I couldn't figure out how to properly do the filters I simplified the system. Can we please have a walk through on how to filter so that an item only goes to one destination and the like? the filters are pretty difficult to understand
![image](https://user-images.githubusercontent.com/5807272/121260081-1f2e0700-c86e-11eb-8b94-9326eeb58ed3.png)

**Comment by henkelmax** [comment]
This filtering system seems a bit counter intuitive at first, but it allows for very complicated routing setups. Unfortunately due to this, simple setups are a little more complicated.
To do a simple filter destination setup, I would recommend setting it to blacklist and use inverted filters.

**Comment by jarquafelmu** [comment]
How would you set up the black list and the inverted filters? If i want iron dust to only go to chest B of chests A, B, C

would i blacklist iron dust and then create an inverted rule saying iron dust goes to chest b?
