### ISSUE TITLE
Is there a max capacity for a pipe?

### ISSUE THREAD

**Issue by jarquafelmu** [henkelmax/pipez#47]
Is there a maximum capacity for a pipe? I know that with the Ultimate Pipe upgrade the most it can send is 131,072 FE/t but is that just for that connection or for the pipe itself?

If I have 4 ultimate connections feeding into one pipe, can the pipe handle 524,288 FE/t or would it only be able to send 131,072 FE/t?

**Comment by henkelmax** [comment]
The pipe itself doesn't store anything. It just has transfer speeds. You can change them in the config.
