### ISSUE TITLE
Improved Upgrade Recipes Do Not Work as Intended

### ISSUE THREAD

**Issue by Darkosto** [henkelmax/pipez#5]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
When crafting the Improved Upgrade the previous upgrade item overrides the result

**Steps to reproduce the issue**
1. Craft the Improved Upgrade
2. The result will be the Basic Upgrade

**Expected behavior**
For the improved upgrade to be craftable

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.0.43
- Mod version: 1.16.5-1.1.1

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Thank you for reporting this issue. It should be fixed in the next version.

**Comment by xenoflot** [comment]
I encountered this problem in Refined Storage crafting grids, but they crafted just fine in a vanilla or other modded bench.

That may be relevant but may already be addressed by this fix. Cheers!

**Comment by henkelmax** [comment]
You might clear this recipe template and create it again. Refined storage caches the inputs and outputs.
