### ISSUE TITLE
[Possible mod conflicts] Pipes forgetting their connections with Mekanism multi-block tanks. 

### ISSUE THREAD

**Issue by jarquafelmu** [henkelmax/pipez#50]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
I set energy pipez to output from mekanism multi-block tanks. In this case the induction matrix. I spend some time away and sometimes when I come back the connection is forgotten so the pipes are no longer set to output. Not only that but my ultimate upgrades for the pipe connections keep disappearing.

I have also had this happen with universal pipez extracting from mekanism dynamic tanks and fluid pipez extracting from mekanism thermal evaporation structures.

I don't know if this is a problem with pipez forgetting or mekanism or even entity culling so I will reference this ticket in all three issue trackers.

**Steps to reproduce the issue**
1. Build a mekanism multi-block tank
2. Put some valves on it. If necessary change valves to be output
3. Attach the correct pipe to the tank. 
4. Wait doing other things without the area being looked at?

**Expected behavior**
I expect that the pipes to continue to extract from the mekanism structures. instead either a) my ME system shuts down because I have no power because all of my energy extraction pipes have forgotten that they are extraction and have gone back to being input. Or b) my dynamic tanks now have the wrong fluid because the extraction universal pipe forgot itself and is now pumping things into the tank.

**Log files**
[Client latest.log] https://gist.github.com/jarquafelmu/427b2fa1524d0d2b7d35b43c99dce28d
[Server log] https://gist.github.com/jarquafelmu/6fce3093de5778d860574ce6db4dfb6f
[Server debug log] https://gist.github.com/jarquafelmu/ae54df6c8735c4fb62930fc6e5779c79
[Server latest.log] https://gist.github.com/jarquafelmu/31eea2fd0335b87eada6f78f061ad6f8

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.24
- Mod version: Pipez 1.2.7

**Other mods**
- Mekanism 10.0.21.448
- EntityCulling 2.1.6

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/5807272/121785754-ea28f980-cb78-11eb-96cb-58091ddce9fb.png)
![image](https://user-images.githubusercontent.com/5807272/121785768-fa40d900-cb78-11eb-8399-38af4183cd31.png)
![image](https://user-images.githubusercontent.com/5807272/121785774-03ca4100-cb79-11eb-8051-e74131093835.png)

**Comment by henkelmax** [comment]
This is a general mekanism problem. Everythime the structure gets loaded it is invalid for a tick or so. This causes the pipe to not see a valid connection there and disconnects itself.
We already tried a dirty workaround for this (that maybe also introduces some side effects) to wait a few tick after loading the pipe to check if it is valid. But even this didn't always work.
Maybe the mekanism guys can do something about it, but I'm not wasting my time working around this messy system.

**Comment by jarquafelmu** [comment]
thanks for your input henkel, hopefully the mekanism folks will be able to fix this on their end

**Comment by TronWoWGamer** [comment]
I have the same problem with multiblock tank and fluid pipes.  If I break one of the pipes and replace it, the block update fixes everything, but it happens every time I log in for the first time.

**Comment by henkelmax** [comment]
This has been fixed in later versions.
