### ISSUE TITLE
Limit items sent to an inventory

### ISSUE THREAD

**Issue by Midius** [henkelmax/pipez#53]
**Is your feature request related to a problem? Please describe.**
Currently the Pipes will sent all items until all slots are filled. This generates problems with machines, like Alloy Smelters, that need different materials or any other machines with multiple inputs and no sidedness or internal recipe check. You could also use this to automatically stock an Ender-Chest with a connected Ender-Pouch with certain Items for Personal use etc.

**Describe the solution you'd like**
There should be a filter option to specify the exact amount being sent by the pipes and the amount that should be in the Inventory, only sending more items if the amount is less than the specified amount.

**Comment by henkelmax** [comment]
This is not possible, sorry.

**Comment by Midius** [comment]
Would it be possible to add a pulse mode to the redstone control and the ability to reduce the amount of items transferred per operation?

In that case you could use 2 filters with the same destination that would be triggerd on a redstone puls. This way you could at least ensure to get the right ratios of the items you need.

**Comment by henkelmax** [comment]
Pipes have a redstone mode. You can use that in combination with comparators.
