### ISSUE TITLE
After Server Restart pipes disconnect from certain blocks. 

### ISSUE THREAD

**Issue by Profit0004** [henkelmax/pipez#57]
In ATM6 Modpack when pipes connect to mekanism in chunkloaded squares, they quite often will disconnect and throw their upgrade cards out when the chunk is loaded.   Super annoying with the more expensive upgrade cards.   Super duper annoying when the server's host has disabled mechanism pipes for these.

**Comment by henkelmax** [comment]
Please fill out the bug template.

**Comment by Profit0004** [comment]
Fine... Call it invalid if you want... Hide the fact it is broken.

**Comment by henkelmax** [comment]
> Fine... Call it invalid if you want... Hide the fact it is broken.

Just create a new issue and follow the template. You don't have to get angry.

**Comment by enderger** [comment]
> Fine... Call it invalid if you want... Hide the fact it is broken.

You do know that software project management takes effort, and taking 5 minutes to use the issue template makes the job of fixing it that much easier. If you are annoyed so much by the process of submitting a bug report with the template, /fork it and fix it yourself/. I apologise if I come off as brash, however I find that the attitude displayed here was utterly disrespectful.

**Comment by Profit0004** [comment]
You are fine to come off with attitude just remember why I AM COMING OFF WITH ATTITUDE and disrespect, this mod is the only allowed piping segments on many servers because they believed the admins believed the pitch that its somehow much faster *The servers still run sub 2 TPS all the time so obviously they were wrong, but they do not go back to using mods with pipes that work.  Servers deal with the issues from this mod and it affects every player on them, I report the issue but I didn't use some ridiculous template because it is nearly 100% irrelevant to the issue but yet people hide behind it rather than fixing it.   This mod ruins my experience and lots of other people's experience on open servers with constantly breaking machinery and piping.   I honestly don't want this mod fixed I would prefer to see it deleted and go back to the original default things like mekanism pipes that actually worked but I do not have such an option if I want to play on the public servers.  So... Here we are.

**Comment by henkelmax** [comment]
Dude...
I can't help you if I don't have the relevant information. Fill out the template or leave it. There is really no reason to get angry.
