### ISSUE TITLE
Power transfer rates half with each new connection

### ISSUE THREAD

**Issue by Vipered** [henkelmax/pipez#65]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
I don't know if this is a bug or intentional game design. Using the power pipes, if I pull power from a source and then connect it to any block that uses power, it will transfer at whatever the cable is rated for. The problem occurs when you start adding more devices that use power. For each new device that is connected to the cable, the transfer rate of power halfs. So if I have a base with 20 or 40 things that need power, my power transfer rate is 20 or 40 times less than it would be at maximum. This means, if I want to keep the transfer of power up, I need to make multiple power sources for each individual item that needs power.
Is this intended behaviour?

**Steps to reproduce the issue**
Connect Energy pipe to and power source and connect it to more than 1 device to see that the energy transfer rate is halfed with each and every new connection

**Expected behavior**
As other energy pipes, I would not expect the transfer rates to half with each new machine connection

**Log files**
Logs irrelevant.

**Versions**
pipez-1.16.5-1.2.7.jar

**Other mods**
Any mod that accepts RF
**Screenshots (Optional)**
Screenshots of the issue.

**Comment by Vipered** [comment]
I'd just like to add, this would be fine if all of those blocks were actively using power, it would make sense if you have a 1000rf throughput cable going to 2 machines that they would each be able to recieve 500rf each when they are both running, but it halfs if even if they are not actively losing the power

**Comment by henkelmax** [comment]
I double checked everything and it works like intended.
