### ISSUE TITLE
[1.17.1] Crashes when loaded with latest The One Probe update.

### ISSUE THREAD

**Issue by Gbergz** [henkelmax/pipez#66]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
The game crashes when loaded with latest **The One Probe** update.

**Steps to reproduce the issue**
1. Install Pipez
2. Install The One Probe
3. Be on Forge 37.0.43
4. Game crashes. (The One Probe encountered an error during the process_imc event phase.)

**Expected behavior**
That the game can boot when The One Probe is installed together with Pipez.

**Log files**
https://gist.github.com/Gbergz/65a0c0760d8c5ac9c7c28e253a3dca14

**Versions**
- Minecraft version 1.17.1
- Forge version 37.0.43
- Pipez version 1.0.0 | https://www.curseforge.com/minecraft/mc-mods/pipez/files/3408432
- The One Probe version 4.0.2 | https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files/3430022

**Other mods**
The One Probe & Pipez

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/26634554/130472476-95f905fd-5335-4e1d-a3c5-8a9a872f67ee.png)

**Comment by henkelmax** [comment]
Thank you for reporting this issue. It should be fixed in the next version.
