### ISSUE TITLE
Camouflaged Pipez

### ISSUE THREAD

**Issue by Mendanbar** [henkelmax/pipez#67]
**Is your feature request related to a problem? Please describe.**
No problem, just a nice QoL suggestion

**Describe the solution you'd like**
It would be great if Pipez had the ability to camouflage or do facades.  I think in addition to performance, the ability to hide the pipes would set it apart as a go-to all-in-one transportation mod.

**Describe alternatives you've considered**
I've tried x-net, which has facades... and it's just too complex for basic routing.  Pretty Pipes has camouflage, but they are terrible to use and configure, and not performance friendly at all. Pneumaticraft has logistical options and a camouflage tool, but it requires some heavy investment in the mod to get to that level.  Refined Storage had covers in the works once upon a time, but that's looking less and less likely every day.  In short, there's no good option out there right now.

**Additional context**
I'm trying to make the case for Pipez to be considered for Enigmatica 6, and I think the one thing that would really set it apart would be some form of camouflage.

**Comment by henkelmax** [comment]
This won't get added, since this would lead to a poor performance. The whole purpose of this mod is to have a good performance. If you want fancy pipes, use any other pipe/cable mod.

**Comment by digital-pet** [comment]
This is disappointing, besides just aesthetics it means you have to create extremely bulky spaghetti to keep pipes from interacting with each other.

**Comment by henkelmax** [comment]
Visuals it simply not a priority with this mod.

**Comment by digital-pet** [comment]
I understand not prioritizing looks and having opaque pipes is wonderful but this omission also makes it less usable for my use case, like in comparison to thermals' itemducts which I was using back in 1.12, the ability to slap a cover on a pipe and have it never try to connect to any pipe or inventory on that side again was extremely helpful.

**Comment by thebikwirm** [comment]
why dont you make it a config option that is disabled by default

**Comment by henkelmax** [comment]
Only block entities can have special renderers. But only the extracting part of the pipe is a block entity. Its simply not possible without sacrificing performance.
