### ISSUE TITLE
Fluid Pipes cause an exceptional amount of TPS lag with MrCrayfish's Vehicles mod's Fluid Mixer 

### ISSUE THREAD

**Issue by Dandas52** [henkelmax/pipez#68]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Using fluid pipes to transfer liquids into a MrCrayfish's Vehicles mod fluid mixer can cause a 7-9 TPS drop. A profiler shows that the pipes going into the mixer take up about 70% of processing time for all tile entities. 

**Steps to reproduce the issue**
1. Attach fluid pipes to Fluid Extractors connected to a fluid mixer.
2. TPS drops. 

**Expected behavior**
Lag-free fluid transfer. 

**Profiler Report**
https://spark.lucko.me/5huOGIxM1m

**Versions**
1.16.5
MCV 0.45.2
Pipez 1.2.7

**Comment by henkelmax** [comment]
> https://spark.lucko.me/5huOGIxM1m

Your link is invalid
