### ISSUE TITLE
Incompatibility with RFTools Power

### ISSUE THREAD

**Issue by Frostiikiller** [henkelmax/pipez#7]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
1. Place RFTools Powercell (medium)
2. Place energy pipe, set to extract with pipe wrench
3. Connect other end to any power using device
4. Notice the power using device does not receive power

**Expected behavior**
Expect the inserting end of pipe to have energy, but it does not

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.0.46
- Mod version: pipez-1.16.5-1.1.2.jar

**Other mods**
Playing with the All The Mods 6 pack

**Comment by henkelmax** [comment]
This is because the generators of this mod are pushing energy, but not providing energy. Maybe report this to their issue tracker.
