### ISSUE TITLE
If I’m just stupid please let me know.

### ISSUE THREAD

**Issue by MrLyca** [henkelmax/pipez#73]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
When messing around with the mod (in 1.16.6) I was attempting to build a compact two furnace smelter. Then attempting to sort inputs to certain chests I’ve discovered the fill priority (fill closest, fill furthest, round robin, random) supersedes the destination filter.

**Steps to reproduce the issue**
1. Place three chests, one being input, the other two being output A, and output B
2. Hook the pipez up respectively, pulling from in to A and B in the same line and proper upgrades.
3. Set destination to the side of the furthest output chest to the side of that block the pipe is connected to.
4. Input filter for item X with the destination for output B.
5. Watch as it only fills output A

**Expected behavior**
I would think destinations would supersede fill priority otherwise machine with these pipes become wildly impractical in a small scale.

**Log files**
I’m unaware of how to obtain game log though I’m more than happy to provide if absolutely needed. If that’s the case I’ll look into how and submit it to you as well.

**Versions**
- Minecraft 1.16.5
- Forge 36.2.0 
- Mod 1.16.5-1.2.7

**Other mods**
Bookshelf 10.2.27
Botania 419
Cofh core 1.3.1
Comforts 4.0.1.3
Cucumber 4.1.10
Curios 4.0.5.3
Darkutilities 8.0.10
Exnhiliosequentia 1.16-20210826035238
Fast leaf decay-v25
Hats 10.3.1
Ichunutil 10.4.1
Immersiveengineering 5.0.3-138
Invtweaks 1.16.2-1.0.0
Ironchest 11.2.13
Ironfurnaces 2.7.7
jei 7.7.1.121
Mantle 1.6.123
Mousetweaks-2.14-mc1.16.2
Optifine_1.16.5_HD_U_G8
Oreexcavation 1.8.157
Patchouli
Pickletweaks 1.16.4 5.3.2
Pipez 1.2.7
ProjectE PE1.0.1B
Spartanweaponry-1.16.4-2.1.0-beta-4
Storage drawers-1.16.3-8.3.0
Thermal series
-cultivation 1.3.0
-expansion 1.3.0
-foundation 1.3.2
-innovation 1.3.0
-locomotion 1.3.0
Waystones 7.6.3

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Destinations only apply for that specific output. You would need another destination for the other chest.
