### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Sunekaer** [henkelmax/pipez#74]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Crash with NullPointerException

**Expected behavior**
To not crash

**Log files**
https://paste.feed-the-beast.com/view/a0c40f8e
https://paste.sunekaer.com/ufopazeyod.pl

**Versions**
- Minecraft version 1.16.5
- Forge version 36.2.4
- Mod version pipez-1.16.5-1.2.9.jar

Looks like these two null checks needs to be inverted.
https://github.com/henkelmax/pipez/blob/master/src/main/java/de/maxhenkel/pipez/blocks/tileentity/PipeLogicTileEntity.java#L55
https://github.com/henkelmax/pipez/blob/master/src/main/java/de/maxhenkel/pipez/blocks/tileentity/PipeLogicTileEntity.java#L59

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
