### ISSUE TITLE
Filter slider movement

### ISSUE THREAD

**Issue by JackRuby1** [henkelmax/pipez#76]
**Is your feature request related to a problem? Please describe.**
Allow the player to move the filter slider with the mouse dragging it, instead of just scroll wheel movement. Just scroll wheel movement isn't intuitive for the player to know that it moves past the few filters set.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Josephur** [comment]
I know this is closed, but this is a MUCH needed feature, and something anyone would expect to just work out of the box.  Editing a large list right now is too frustrating.
