### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sunekaer** [henkelmax/pipez#77]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
User has cabled connected to a machine and a tesseract and then removed the machine and its ended up in a loop and crashed

**Expected behavior**
To not loop crash

**Log files**
https://pste.ch/uqacereguw.pl

**Versions**
- Minecraft version: 1.16.5..
- Forge version: 36.2.8
- Mod version: pipez-1.16.5-1.2.10.jar

**Other mods**
tesseract-1.0.23-mc1.16.5.jar

**Comment by Raidobw2** [comment]
If you need more crash logs to solve it, here's another one related to that: https://paste.feed-the-beast.com/view/94ae35b7.
This is a Pipez X Powah interaction, with Pipez being ticked just like with the Tesseract from supermartijn642.
Place a Powah Energy Cable (Basic) next to a Pipez Universal Cable and use the wrench from Pipez on the Universal Cable to connect them, this will replicate the crash.
Source, dupe: FTBTeam/FTB-Modpack-Issues#221
MC & Forge: `1.16.5-36.2.8`.
`Powah-1.16.5-2.3.16.jar` & `pipez-1.16.5-1.2.10.jar`.

**Comment by ogmacwinux** [comment]
I just encountered this error on FTB OceanBlock 1.7.0, but with a Pipez Fluid Pipe connected on top of an Industrial Foregoing Enchantment Applicator with a Powah Energy Cable (Basic) connected below the machine. Tested on a freshly made Singleplayer Creative world.

When there is no Powah cable connected to the machines, Fluid Pipe works as expected. Screenshot: 
![2021-11-10_08 32 05](https://user-images.githubusercontent.com/61723329/141102942-43ac9a16-9b43-4e71-b405-71c1b5148633.png)

When there is a Powah cable connected to the machines, world immediately crashes when the Fluid Pipe is set to extract. Screenshot: 
![2021-11-10_08 34 09](https://user-images.githubusercontent.com/61723329/141103016-c0243579-f61f-41a1-a773-01ec4dc9fa64.png)

Crash report: https://paste.feed-the-beast.com/view/d2ef4066
Modpack: `FTB OceanBlock 1.7.0`
Minecraft: `1.16.5`
Forge: `36.2.9`
Pipez: `pipez-1.16.5-1.2.9.jar`
Powah: `Powah-1.16.5-2.3.16.jar`

**Comment by ogmacwinux** [comment]
Hi, I re-checked my specific issue described above and the crash isn't happening anymore after properly updating the modpack.

Modpack: `FTB OceanBlock 1.9.0`
Minecraft: `1.16.5`
Forge: `36.2.9`
Pipez: `pipez-1.16.5-1.2.13.jar`
Powah: `Powah-1.16.5-2.3.16.jar`
