### ISSUE TITLE
Filter destination ignores setup

### ISSUE THREAD

**Issue by LuciusV** [henkelmax/pipez#8]
**Versions**
- Minecraft version 1.16.5
- Forge version  36.0.39
- Mod version 1.16.5-1.1.2

I have setup as shown on screenshots:
I have incomping flow of Mystical Agriculture _Essences_ and _Seeds_ going into **buffer barrel** with single pipez output (advanced pipe upgrade). From that output _Essences_ are configured to go to **Crafter**, and _Seeds_ to **Seeds Reprocessor**.
I have another advanced pipez pulling _Essences_ produced by **Seeds Reprocessor** into **Crafter**
Problem is that some _Essences_ go to input of **Seeds Reprocessor**, despite only **Crafter** is whitelisted for _Essences_.
Blacklisting  _Essences_ from going to **Seeds Reprocessor** does not help.

**Screenshots (Optional)**
Screenshots of the issue:

![2021-03-14_22 00 51](https://user-images.githubusercontent.com/11925386/111071925-5f057c80-8513-11eb-9ac5-9d1489a774b5.png)
![2021-03-14_22 01 04](https://user-images.githubusercontent.com/11925386/111071927-63319a00-8513-11eb-9d08-1d1a7143be6a.png)
![2021-03-14_22 01 10](https://user-images.githubusercontent.com/11925386/111071932-66c52100-8513-11eb-8e0f-088c0e510426.png)
![2021-03-14_22 17 15](https://user-images.githubusercontent.com/11925386/111071937-6a58a800-8513-11eb-8ad3-72c833eca3b6.png)

**Comment by LuciusV** [comment]
It does not happen if I blacklist Essences from Seeds Reprocessor output go back to itself, so they just take shortest path instead of following existing whitelisted path to crafter. Still its not logical that whitelist does not have priority leaving place to situation like that. In case that there would be more destinations, routing like this make logistics impossible with only whitelists and blacklisting manually  all possible destinations is extremely time consuming.

**Comment by henkelmax** [comment]
Your seed reprocessor still allows iron essence to be inserted. You either need a blacklist for it on all other destinations or make a whitelist for other items on all other destinations.

**Comment by henkelmax** [comment]
> It does not happen if I blacklist Essences from Seeds Reprocessor output go back to itself, so they just take shortest path instead of following existing whitelisted path to crafter. Still its not logical that whitelist does not have priority leaving place to situation like that. In case that there would be more destinations, routing like this make logistics impossible with only whitelists and blacklisting manually all possible destinations is extremely time consuming.

Whitelists don't mean priority.

**Comment by LuciusV** [comment]
Thank you for explanations. I fixed my setup using blacklists only. Should the issue be closed then?

**Comment by henkelmax** [comment]
Yeah I'm gonna close it.
