### ISSUE TITLE
Gas transfer is very limiting.

### ISSUE THREAD

**Issue by zookeper** [henkelmax/pipez#80]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Someone thought it was okay to put a max transfer rate of 40,000mb of steam per tick than what is used by other mods. the standard high limit is 1 million milli buckets of steam for ultimate use.

**Steps to reproduce the issue**
1. Build a mekanism turbine
2. build a fission reactor.
3. try to transfer the coolant (which is a gas) in quantities of 100 million minimum transfer rate million buckets per tick.
4. watch your reactor never reach it's full potential because the server host disabled all other mods but pipez.

**Expected behavior**
for it to actually transfer gas as other mods intended gas to be transferred. 

**Log files**
There is no log file this is a bug in design.

**Versions**
- Minecraft version 1.16.5
- Forge version 3.2.26
- Mod version atm-6 1.8.5

**Other mods**
ATM 6

**Screenshots (Optional)**
Oh you want to see my melted reactor? okay. 
![meltdown](https://user-images.githubusercontent.com/4263760/139599771-0ab87afb-8b93-4e9c-839e-6c6304d30a4b.png)

**Comment by henkelmax** [comment]
What is the bug??

**Comment by zookeper** [comment]
It appears that pipez mod is resetting its connection within random io ports in multiblocks most notably on mekanism multiblocks. The pipe ultimate upgrade transfers steam at its intended rate however when it tries to send other gas like sodium or heated waste from a reactor it appears limited as you require 8 connections per input/output face which is only good to transfer 48mb/t of either sodium or heated waste. This is excessive as the reactor now has 16 ports on it 8 for input 8 for output when only 8 in total should be needed 4 for input 4 for output at that low of a mb/t

To note. the reactors are melting down because pipe connections with ult upgrades are either popping out or being rejected. Several times I have had to break the pipes and take out the ultimate upgrades to reinstall them so the reactor will eject heated waste properly literally every restart or crash. This also happens with ult upgrades connected to dimensional cells and Energy cell from mekanism configured to output energy.

Any reactor with pipes installed and configured with ult upgrades in it, will melt down if the server restarts or crashes if it has fuel in it, regardless of the logic that is setup.

**Comment by henkelmax** [comment]
Yeah, the upgrades popping out is actually not fixable on our side. It is mekanism, not validating their multiblock structure after loading chunks (They usually validate after a few ticks, thus the pipes disconnect). Their implementation is so broken, that we have no real way of fixing this.

**Comment by zookeper** [comment]
Yeah I had figured this was the case. So all I can do is post bug reports. I did request a feature to have the reactor turn off on mekanisms pack every restart because they are literally melting down every restart or crash. (you can imagine how many times ive had to rebuild a reactor because the public server which isn't very stable on this pack to begin with)

Btw your mod works good. no lag. haven't ran into any other issues than the dang multiblock disconnection bug.

So thank you for that because all other pipes seem to cause a plethora of lag on public multiplayer servers.

**Comment by zookeper** [comment]
Could you please double check and verify that pipes ultimate upgrade is indeed transferring sodium and heated waste at it's intended rate because it just seems ridiculously to have to put as many connection ports as I have needed. If they are, the only thing I could request is that the gas rate of transfer is increased.

**Comment by henkelmax** [comment]
> Could you please double check and verify that pipes ultimate upgrade is indeed transferring sodium and heated waste at it's intended rate because it just seems ridiculously to have to put as many connection ports as I have needed. If they are, the only thing I could request is that the gas rate of transfer is increased.

This might just be a configuration issue... Double check the transfer rates in the config.

**Comment by zookeper** [comment]
Server owner has said it was not changed. For better understanding of what's happening I am playing on a single player world on atm 6-1.8.9 I will try to troubleshoot further what exactly is the issue.
