### ISSUE TITLE
Item ID filter allowing all items when using blank NBT

### ISSUE THREAD

**Issue by kingchills** [henkelmax/pipez#82]
**Bug description**
Creating item filter with blank NBT string causes all items to pass through.  I believe this may be related to the fix for #79, as using the enchantment NBT string (`{Enchantments:[{}]}`) works as expected in the following scenario.

**Steps to reproduce the issue**
1. Create input chest containing 1 stack of bones, 1 stack of arrows, 1 Iron Leggings Enchanted, and 1 Iron Leggings not enchanted.
2. Attach an item pipe to the input chest, and using a wrench change the side touching the input chest to pull items.
3. Open the GUI and insert an Advanced Upgrade.
4. Click the Blacklist icon
5. Click Add, and add the iron leggings, and set the NBT Data to `{}` then click inverse, and submit.
6. Place an output chest
7. Observer All items in output chest.

**Expected behavior**
This filter should only allow the two pairs of iron leggings through, but instead it allows all items through.

**Log files**
https://gist.github.com/kingchills/cd539433596421d7fadd8acc9a3ab6bb

**Versions**
- Minecraft version - 1.16.5
- Forge version - 36.2.8
- Mod version - 1.2.12

**Other mods**
None

**Screenshots (Optional)**
I tried to upload screens here, but it kept giving me an upload error, probably my garbage internet.  Here's a link to an imgur album

https://imgur.com/a/UNmuGnd

**Comment by kingchills** [comment]
A slight update I just found.  If I type in the ID/Tag of an item, and don't put anything in the NBT data, it seems to function correctly.  But if I click an Item into the filter, and delete the NBT string, when I hit submit it restores the previous NBT string.

**Comment by henkelmax** [comment]
Entering `{}` as a tag is the same as leaving the field empty and thus ignoring it.
