### ISSUE TITLE
Destination Tool

### ISSUE THREAD

**Issue by MaxxiKing** [henkelmax/pipez#83]
I don't know if I am just stupid or can't find the resolution for it. I made a huge item sorting system, where i have 1 chest where i put in all the items, and about 100 chests where they are going to be distributed. I set a filter with the destination tool to a certain chest. But if I put the whitelisted item in, it still goes to the nearest chest - all the time. What am I doing wrong? Or is this supposed to be like this?

**Comment by henkelmax** [comment]
Filters for certain destinations ONLY apply for this destination. Double inverting filters would solve your problem.

**Comment by MaxxiKing** [comment]
What do you mean by double inverting? Do I have to blacklist this item in every other chest?

**Comment by henkelmax** [comment]
Blacklist + inverted filters

**Comment by MaxxiKing** [comment]
oh this worked. thanks a lot :)
