### ISSUE TITLE
Made a mistake

### ISSUE THREAD

**Issue by MaxxiKing** [henkelmax/pipez#84]
Hello! 

I made a big mistake and clicked my chests with the destination tool from the wrong site. Now my question, which file gets edited if I add an item to a filter? maybe there is a chance i can change the setting via the file? Thanks in advance.

**Comment by henkelmax** [comment]
I have no clue what you mean.
There is nothing that can't be undone ingame.

**Comment by MaxxiKing** [comment]
I mean that every single thing i do in minecraft has to be saved in a file somewhere. Maybe i can find where this kind of data is stored so i can switch every "facing south" to "facing north"

**Comment by MaxxiKing** [comment]
Already found it, ty :)
