### ISSUE TITLE
Oceanblock 1.9 crash with pipez and tesseract interaction

### ISSUE THREAD

**Issue by Warzer1** [henkelmax/pipez#85]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
When connecting pipez though a tesseract on a power channel and setting the export on the energy or universal pipe game crashes.

**Steps to reproduce the issue**
1. place 2 tesseracts 1 block away, configure a power channel
2. place either energy or universal pipez cable between them.
3. using pipez wrench set one side to export. (i set left side in below screenshot before crash)
4. Server crashes after a few seconds
Description: Ticking block entity

java.lang.StackOverflowError: Ticking block entity

**Expected behavior**
not crash and transfer power.

**Log files**
crash log attached.
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Modpack FTB OceanBlock 1.9
- Minecraft version:1.16.5
- Forge version: 36.2.9
- Mod version: 
- pipez 1.16.5-1.2.13
- Tesseract 1.0.24-mc1.16

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
I need to figure out how to do this step if necessary.
**comments
-tested fluid and item they don't seem to have this issue.  Only happens when trying to extract.  

**Screenshots (Optional)**
Screenshots of the issue
![2021-11-29_09 29 40](https://user-images.githubusercontent.com/23535514/143897431-a122eaee-a1b0-40af-be19-16585990257e.png)
[crash-2021-11-29_09.29.45-server.txt](https://github.com/henkelmax/pipez/files/7619255/crash-2021-11-29_09.29.45-server.txt)
.

**Comment by Piratkopia13** [comment]
We experienced this crash on our All The Mods 7 server today. It's a very bad crash since it will continue to hard crash the server every time the area is loaded. The only fix was to open up the world in an external editor and remove the blocks.

**Comment by Piratkopia13** [comment]
To repro it seems like the power channel set in the tesseracts has to be connected to power in the other end. In my case it was connected to a running reactor.

**Comment by henkelmax** [comment]
Closed with https://github.com/SuperMartijn642/Tesseract/issues/35
