### ISSUE TITLE
[1.16.5] Gas Pipe is missing

### ISSUE THREAD

**Issue by SMN47** [henkelmax/pipez#88]
**Bug description**
On a client side gas pipe is missing. On a server side an error pops up. In short it says: 

_[02dec2021 23:21:20.440] [Worker-Main1/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table pipez:blocks/gas_pipe
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'pipez:gas_pipe'_ 

**Expected behavior**
No server error and no missing items.

**Log files**
https://gist.github.com/SMN47/99b1aa027bab9734492b71f381ab1851
Line 592 and further

**Versions**
- Minecraft version 1.16.5
- Forge version client 36.2.8, server 36.2.19
- Mod 1.2.13

**Other mods**
Listed in attached screenshot (server side)
The only tech mods are Thermal Series:

![photo_2021-12-03_00-56-45](https://user-images.githubusercontent.com/11785385/144516807-0ef9898d-9af2-473b-a0b7-ef711c0bb4e1.jpg)

**Comment by henkelmax** [comment]
Gas pipes only exist if you have Mekanism installed, obviously.
