### ISSUE TITLE
Extract and Insert from the same side for universal pipe

### ISSUE THREAD

**Issue by WhitePhant0m** [henkelmax/pipez#9]
Would be pretty nice if you could toggle the individual parts of the Universal pipe to insert/extract
ex. extracting items but inserting power and fluid

**Comment by WhitePhant0m** [comment]
and maybe also allow universal pipes to connect to other pipes? would be nice to use them as bridges for other pipes, so i wouldn't need to do this
![image](https://user-images.githubusercontent.com/33400200/111088881-02fe2080-8532-11eb-9e08-85689704488a.png)

**Comment by henkelmax** [comment]
Unfortunately, due to the optimizations and the general implementation of the pipes, this is not possible.
