### ISSUE TITLE
Upgrade Duplication 

### ISSUE THREAD

**Issue by davdavy** [henkelmax/pipez#90]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
 Pipe Upgrade duplication glitch with 'Bag of Yurting' mod.

**Steps to reproduce the issue**
1. Grab 'Bag of Yurting 3x3x3"
2. Use the bag of Yurting to pick up a pipe that is attached to a chest with a 'Pipez' upgrade in it.

**Expected behavior**
You pick up the pipe and chest. The upgrade drops when you pick it up, but stays in the pipe when placing down.
Works with any chest/machine and with any upgrade.

**Log files**
(https://github.com/henkelmax/pipez/files/7647001/latest.log)

**Versions**
- Minecraft version 1.16.5
- Forge version 36.2.8
- Mod version 1.2.13

**Other mods**
ATM 6 Version 1.8.10

**Screenshots (Optional)**

https://user-images.githubusercontent.com/4213704/144551105-e707b637-de67-44d4-85bc-00b69fb81e89.mp4

**Comment by henkelmax** [comment]
We don't support mods that let you pick up blocks with nbt data. It completely breaks the mod, since everything is coordinate based and based on which block is besides it.
Report it to the mod dev of this bag thing. Maybe they have a blacklist.
