### ISSUE TITLE
Cauldron & Fluid pipes

### ISSUE THREAD

**Issue by oxodao** [henkelmax/pipez#93]
**Bug description**
I'm not sure if this  is intended or not, but the fluid pipes do not connect to the cauldron, thus preventing the creation of infinite lava generator in 1.17+

**Steps to reproduce the issue**
1. Put a cauldron next to a pipe
2. does not connect

**Expected behavior**
The pipe should let the player input and output fluid from the cauldron

**Versions**
- 1.17.1
- 37.1.1
- 1.17.1-1.0.6, Replicated in 1.17.1-1.0.10

**Other mods**
Lots of mods but I'm pretty sure none causes this issue as the only mod with fluid stuff other than Pipez is ITank

**Screenshots (Optional)**
![https://u.oxodao.fr/pipez_report.png](https://u.oxodao.fr/pipez_report.png)

**Comment by henkelmax** [comment]
Completely intended.
