### ISSUE TITLE
Chest Meltdown

### ISSUE THREAD

**Issue by wwilsonn91** [henkelmax/pipez#95]
I'm not sure how to properly describe what's happening. This glitch is not causing crashing, but does appear to be impacting performance slightly and impacts usability should one wish to draw ore from the given chest.

Selected pipe is an item pipe with the infinity upgrade.
I have filters set up to draw coal, coal blocks, and every ore type into the furnace in their appropriate locations.
I have added full (64x) item stacks of each ore type into the chest.
The pipes are pulling the items out of the chest, running them through the pipe, then back into the chest.

Linked [here](https://youtu.be/eEPpUfVwoDc), is a YouTube video of the event and setup, seeing as I feel that I can't properly explain the situation.

**Comment by henkelmax** [comment]
Infinity upgrades are very laggy, because they try to move an infinite amount of items. That's why they don't have a recipe.

**Comment by wwilsonn91** [comment]
> Infinity upgrades are very laggy, because they try to move an infinite amount of items. That's why they don't have a recipe.

The performance issue is minor, and was absolutely not the topic of concern, as was clearly stated. The infinity upgrade, while providing the most notable impact, is not the issue either.

I switched to the ultimate upgrade, given your "helpful" feedback, upon which, this is what I observed:
- The stacks stopped rotating. (AWESOME!)
- Any stacks of the same type (assuming that you've got a partial stack) will flip the items back and fourth between the given stacks.

Example:
Two stacks of gold ore, one with 20 items and the other with 64.
Placing these two stacks into the chest will result in the 64x stack bouncing back and fourth between the two slots.

**Comment by henkelmax** [comment]
Yes, because you feed the items out of the chest back into it. Of course it will go into another slot.

**Comment by wwilsonn91** [comment]
> Yes, because you feed the items out of the chest back into it. Of course it will go into another slot.

Not even close to a true statement.
The item should be moved to the first available non-full space that is available for that item type, so the 64 stack should be moved toward the beginning - this would be within expectations. The items bouncing back and fourth, on the other hand, is a different story.

For example, if you have stacks of 0, 20, then 64, then the order should become 64, 20, 0
not
- 64, 20, 0
- 20, 64, 0
- 64, 20, 0

Obviously, 0 would denote an empty slot.

**Comment by henkelmax** [comment]
That's not how the mod works, basically it instantly transfers stuff without a intermediary storage, so the item it is taking out is actually still in there when it inserts it again.

**Comment by wwilsonn91** [comment]
> That's not how the mod works, basically it instantly transfers stuff without a intermediary storage, so the item it is taking out is actually still in there when it inserts it again.

So, essentially, "It's not broken, it's just queer."? Awesome. Great policy. This here is a perfect example of why I hate dealing with developers... :/ 

Whether it uses an intermediary storage or not, the slot that it's taking the item from still very much exists.
If you ask me, it's not that hard to insert a couple (literally 2, if I'm not mistaken) of conditional statements to check if the item is already in its most appropriate position, and not move it should that check return true..
