### ISSUE TITLE
Pipez filtering does not understand potions from water or lingering from splash

### ISSUE THREAD

**Issue by Pultex** [henkelmax/pipez#96]
**Bug description**
NBT data or Meta data not read correct on potions
Pipez will not filter a potion with exact settings or normal settings that is a "awkward lingering potion" to any location

Pipez will not filter the difference on white list from a "water bottle" or a "awkward potion" or a "awkward splash potion"
Pipez will filter an inverted white listed or black listed  "water bottle", "awkward potion", or "awkward splash potion"
[ HOW CAN THIS BE POSSIBLE ]

**Steps to reproduce the issue**
1. place chest down with water bottles or other not filtering potions
2. place pipez on side of chest into side of brewer
3. place pipez under brewer with filter setting for one of the potions into side new brewer
4. see water or awkward potion sent to the last brewer

**Expected behavior**
The NBT and Meta data be read correctly like Refined Storage can filter them

**Log files**
there is no error just incorrect behavior 

**Versions**
- Minecraft version 1.16.5
- Forge version 1.16.5-forge-36.2.20
- Mod version pipez-1.16.5-1.2.12  [future versions list only translation support at this time]

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Works as intended in the latest version.
