### ISSUE TITLE
Full Block Pipes

### ISSUE THREAD

**Issue by ramonGonzEdu** [henkelmax/pipez#99]
**Is your feature request related to a problem? Please describe.**
Whenever I want to use pipes for a large area (for example a power grid), i have to leave ugly gaps in the walls where the pipes go in.

**Describe the solution you'd like**
A new variant of each pipe which takes up a full block and can't push or pull. it would have the same behavior of a normal pipe of that kind.

**Describe alternatives you've considered**
Covering up the pipe for fluid and item.
Using a battery buffer for energy.

**Additional Context**
Another option would be to add something like covers and hollow covers.

**Comment by Maxter-Max** [comment]
These gaps can also be problematic as they can allow small entities like baby bees to fly through, so being able to have pipes that also function as walls even if it's not customizable in texture or colour would still be nice.

**Comment by henkelmax** [comment]
Won't happen, sorry.
